import { spawnSync } from "node:child_process"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { runtimeAssets } from "../../convex/runtime/_generated/assets.ts"
import { root } from "./paths.ts"

const generatedPath = path.join(
  root,
  "convex/playbooks/blueprints/generated.ts"
)

export async function compilePlaybookBlueprints(checkMode: boolean) {
  const runtime = await fs.mkdtemp(path.join(os.tmpdir(), "milo-blueprints-"))

  try {
    const template = path.join(runtime, "template")
    await writeFiles(template, runtimeAssets.artifact.template)
    const configPath = path.join(runtime, "builder.json")
    await fs.writeFile(
      configPath,
      JSON.stringify({ artifactTemplatePath: template }),
      "utf8"
    )
    process.env.MILO_WORKSPACE = root
    process.env.MILO_ARTIFACT_BUILDER_CONFIG = configPath

    const { buildArtifact } = await import(
      "../../runtime/source/artifact/builder/index.ts"
    )
    const prep = await buildArtifact([
      {
        path: "src/App.tsx",
        content: await readSource("prep/app.txt"),
      },
      {
        path: "src/contract.ts",
        content: await readSource("prep/contract.txt"),
      },
    ])
    const content = formatGenerated(
      renderGenerated({
        "meeting-prep": {
          access: "personal",
          title: "Meeting prep",
          ...prep,
        },
      })
    )

    if (checkMode) {
      const existing = await fs.readFile(generatedPath, "utf8").catch(() => "")

      if (existing !== content) {
        throw new Error(
          "Playbook blueprints are stale. Run `pnpm blueprints:compile` and commit the result."
        )
      }

      return
    }

    await fs.mkdir(path.dirname(generatedPath), { recursive: true })
    await fs.writeFile(generatedPath, content, "utf8")
  } finally {
    await fs.rm(runtime, { force: true, recursive: true })
  }
}

async function readSource(relativePath: string) {
  return await fs.readFile(
    path.join(root, "contracts/playbooks/blueprints", relativePath),
    "utf8"
  )
}

async function writeFiles(directory: string, files: Record<string, string>) {
  for (const [relativePath, content] of Object.entries(files)) {
    const destination = path.join(directory, relativePath)
    await fs.mkdir(path.dirname(destination), { recursive: true })
    await fs.writeFile(destination, content, "utf8")
  }
}

function renderGenerated(value: unknown) {
  return [
    "/* biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated artifact source */\n",
    "// Generated by scripts/blueprints.ts. Do not edit by hand.\n",
    "export const playbookBlueprints = ",
    JSON.stringify(value, null, 2),
    " as const\n",
  ].join("")
}

function formatGenerated(content: string) {
  const result = spawnSync(
    path.join(root, "node_modules/.bin/biome"),
    ["format", "--stdin-file-path", generatedPath],
    { encoding: "utf8", input: content }
  )

  if (result.status !== 0) {
    throw new Error(result.stderr || "Could not format playbook blueprints.")
  }

  return result.stdout
}
