packages: []

minimumReleaseAge: 0

overrides:
  '@opentelemetry/core': 2.9.0
  '@hey-api/json-schema-ref-parser>js-yaml': 4.3.2
  'giget>tar': 7.5.20
  tsconfck: 3.1.6
  ws: 8.21.1

peerDependencyRules:
  allowedVersions:
    'tsconfck>typescript': ^6.0.0

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
  '@depot/cli': false
  '@openrouter/sdk': false
  bufferutil: false
  utf-8-validate: false
  core-js: false
