/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activations_data from "../activations/data.js";
import type * as approvals_approvals from "../approvals/approvals.js";
import type * as approvals_console from "../approvals/console.js";
import type * as approvals_runtime from "../approvals/runtime.js";
import type * as approvals_slack_blocks from "../approvals/slack/blocks.js";
import type * as approvals_slack_cards from "../approvals/slack/cards.js";
import type * as approvals_slack_decision from "../approvals/slack/decision.js";
import type * as approvals_slack_index from "../approvals/slack/index.js";
import type * as approvals_slack_labels from "../approvals/slack/labels.js";
import type * as approvals_summary from "../approvals/summary.js";
import type * as artifacts_attachments from "../artifacts/attachments.js";
import type * as artifacts_data from "../artifacts/data.js";
import type * as artifacts_mcp from "../artifacts/mcp.js";
import type * as automations_access from "../automations/access.js";
import type * as automations_console from "../automations/console.js";
import type * as automations_cron from "../automations/cron.js";
import type * as automations_data from "../automations/data.js";
import type * as automations_events from "../automations/events.js";
import type * as automations_fire from "../automations/fire.js";
import type * as automations_labels from "../automations/labels.js";
import type * as automations_mcp from "../automations/mcp.js";
import type * as automations_names from "../automations/names.js";
import type * as automations_options from "../automations/options.js";
import type * as automations_options_common from "../automations/options/common.js";
import type * as automations_options_github from "../automations/options/github.js";
import type * as automations_options_google from "../automations/options/google.js";
import type * as automations_options_linear from "../automations/options/linear.js";
import type * as automations_options_microsoft from "../automations/options/microsoft.js";
import type * as automations_options_notion from "../automations/options/notion.js";
import type * as automations_options_providers from "../automations/options/providers.js";
import type * as automations_options_slack from "../automations/options/slack.js";
import type * as automations_providers from "../automations/providers.js";
import type * as automations_read from "../automations/read.js";
import type * as automations_records from "../automations/records.js";
import type * as automations_run from "../automations/run.js";
import type * as automations_search from "../automations/search.js";
import type * as automations_timing from "../automations/timing.js";
import type * as automations_trigger from "../automations/trigger.js";
import type * as automations_write from "../automations/write.js";
import type * as broker_approval_args from "../broker/approval/args.js";
import type * as broker_approval_index from "../broker/approval/index.js";
import type * as broker_artifacts from "../broker/artifacts.js";
import type * as broker_mcp from "../broker/mcp.js";
import type * as broker_milo from "../broker/milo.js";
import type * as broker_tools_common from "../broker/tools/common.js";
import type * as broker_tools_fixtures_artifacts from "../broker/tools/fixtures/artifacts.js";
import type * as broker_tools_github_client from "../broker/tools/github/client.js";
import type * as broker_tools_github_comments from "../broker/tools/github/comments.js";
import type * as broker_tools_github_format from "../broker/tools/github/format.js";
import type * as broker_tools_github_index from "../broker/tools/github/index.js";
import type * as broker_tools_google_drive_format from "../broker/tools/google/drive/format.js";
import type * as broker_tools_google_drive_index from "../broker/tools/google/drive/index.js";
import type * as broker_tools_google_format from "../broker/tools/google/format.js";
import type * as broker_tools_google_gmail from "../broker/tools/google/gmail.js";
import type * as broker_tools_google_index from "../broker/tools/google/index.js";
import type * as broker_tools_google_request from "../broker/tools/google/request.js";
import type * as broker_tools_index from "../broker/tools/index.js";
import type * as broker_tools_linear from "../broker/tools/linear.js";
import type * as broker_tools_microsoft from "../broker/tools/microsoft.js";
import type * as broker_tools_notion from "../broker/tools/notion.js";
import type * as broker_tools_slack_client from "../broker/tools/slack/client.js";
import type * as broker_tools_slack_index from "../broker/tools/slack/index.js";
import type * as broker_tools_slack_upload from "../broker/tools/slack/upload.js";
import type * as events_data from "../events/data.js";
import type * as events_ingest from "../events/ingest.js";
import type * as executions_agent_artifacts from "../executions/agent/artifacts.js";
import type * as executions_agent_authorization from "../executions/agent/authorization.js";
import type * as executions_agent_codex from "../executions/agent/codex.js";
import type * as executions_agent_data from "../executions/agent/data.js";
import type * as executions_agent_prompt_continuation from "../executions/agent/prompt/continuation.js";
import type * as executions_agent_prompt_fixtures from "../executions/agent/prompt/fixtures.js";
import type * as executions_agent_prompt_index from "../executions/agent/prompt/index.js";
import type * as executions_agent_prompt_instructions from "../executions/agent/prompt/instructions.js";
import type * as executions_agent_prompt_integration from "../executions/agent/prompt/integration.js";
import type * as executions_agent_sandbox_e2b from "../executions/agent/sandbox/e2b.js";
import type * as executions_agent_sandbox_execute from "../executions/agent/sandbox/execute.js";
import type * as executions_agent_sandbox_harness from "../executions/agent/sandbox/harness.js";
import type * as executions_agent_sandbox_preflights_index from "../executions/agent/sandbox/preflights/index.js";
import type * as executions_agent_sandbox_preflights_script from "../executions/agent/sandbox/preflights/script.js";
import type * as executions_agent_sandbox_preflights_slack from "../executions/agent/sandbox/preflights/slack.js";
import type * as executions_agent_sandbox_preflights_specs from "../executions/agent/sandbox/preflights/specs.js";
import type * as executions_agent_sandbox_profile from "../executions/agent/sandbox/profile.js";
import type * as executions_agent_sandbox_skills from "../executions/agent/sandbox/skills.js";
import type * as executions_agent_sandbox_trace from "../executions/agent/sandbox/trace.js";
import type * as executions_agent_targets from "../executions/agent/targets.js";
import type * as executions_agent_tokens from "../executions/agent/tokens.js";
import type * as executions_agent_tools_adapter from "../executions/agent/tools/adapter.js";
import type * as executions_agent_tools_assemble from "../executions/agent/tools/assemble.js";
import type * as executions_agent_tools_brokered from "../executions/agent/tools/brokered.js";
import type * as executions_agent_tools_bundles from "../executions/agent/tools/bundles.js";
import type * as executions_agent_tools_definitions from "../executions/agent/tools/definitions.js";
import type * as executions_agent_tools_index from "../executions/agent/tools/index.js";
import type * as executions_agent_tools_milo_bundle from "../executions/agent/tools/milo/bundle.js";
import type * as executions_agent_tools_milo_index from "../executions/agent/tools/milo/index.js";
import type * as executions_agent_tools_milo_script from "../executions/agent/tools/milo/script.js";
import type * as executions_agent_tools_permissions_fixtures from "../executions/agent/tools/permissions/fixtures.js";
import type * as executions_agent_tools_policy from "../executions/agent/tools/policy.js";
import type * as executions_agent_tools_resolve from "../executions/agent/tools/resolve.js";
import type * as executions_agent_tools_schemas_common from "../executions/agent/tools/schemas/common.js";
import type * as executions_agent_tools_schemas_github from "../executions/agent/tools/schemas/github.js";
import type * as executions_agent_tools_schemas_google from "../executions/agent/tools/schemas/google.js";
import type * as executions_agent_tools_schemas_index from "../executions/agent/tools/schemas/index.js";
import type * as executions_agent_tools_schemas_linear from "../executions/agent/tools/schemas/linear.js";
import type * as executions_agent_tools_schemas_microsoft from "../executions/agent/tools/schemas/microsoft.js";
import type * as executions_agent_tools_schemas_milo from "../executions/agent/tools/schemas/milo.js";
import type * as executions_agent_tools_schemas_notion from "../executions/agent/tools/schemas/notion.js";
import type * as executions_agent_tools_schemas_slack from "../executions/agent/tools/schemas/slack.js";
import type * as executions_agent_tools_snapshot from "../executions/agent/tools/snapshot.js";
import type * as executions_agent_tools_types from "../executions/agent/tools/types.js";
import type * as executions_approvals from "../executions/approvals.js";
import type * as executions_console from "../executions/console.js";
import type * as executions_console_context from "../executions/console/context.js";
import type * as executions_console_detail from "../executions/console/detail.js";
import type * as executions_console_details_index from "../executions/console/details/index.js";
import type * as executions_console_display_helpers from "../executions/console/display/helpers.js";
import type * as executions_console_filters from "../executions/console/filters.js";
import type * as executions_console_labels from "../executions/console/labels.js";
import type * as executions_console_origin from "../executions/console/origin.js";
import type * as executions_console_pending from "../executions/console/pending.js";
import type * as executions_console_schedule from "../executions/console/schedule.js";
import type * as executions_console_source from "../executions/console/source.js";
import type * as executions_console_summaries_index from "../executions/console/summaries/index.js";
import type * as executions_console_tools from "../executions/console/tools.js";
import type * as executions_control from "../executions/control.js";
import type * as executions_monitor from "../executions/monitor.js";
import type * as executions_records from "../executions/records.js";
import type * as executions_runtime from "../executions/runtime.js";
import type * as http from "../http.js";
import type * as identity_access from "../identity/access.js";
import type * as identity_clerk from "../identity/clerk.js";
import type * as identity_clerk_data from "../identity/clerk/data.js";
import type * as identity_clerk_profile from "../identity/clerk/profile.js";
import type * as identity_identities from "../identity/identities.js";
import type * as identity_organization from "../identity/organization.js";
import type * as identity_users from "../identity/users.js";
import type * as integrations_data from "../integrations/data.js";
import type * as integrations_disconnect from "../integrations/disconnect.js";
import type * as integrations_lookup from "../integrations/lookup.js";
import type * as integrations_revoke from "../integrations/revoke.js";
import type * as integrations_runtime from "../integrations/runtime.js";
import type * as integrations_status from "../integrations/status.js";
import type * as maintenance_truncate from "../maintenance/truncate.js";
import type * as messages_events from "../messages/events.js";
import type * as messages_ingest from "../messages/ingest.js";
import type * as openrouter_client from "../openrouter/client.js";
import type * as openrouter_index from "../openrouter/index.js";
import type * as permissions_catalog from "../permissions/catalog.js";
import type * as permissions_read from "../permissions/read.js";
import type * as permissions_tools from "../permissions/tools.js";
import type * as prompts_generated from "../prompts/generated.js";
import type * as prompts_render from "../prompts/render.js";
import type * as prompts_time from "../prompts/time.js";
import type * as providers_catalog from "../providers/catalog.js";
import type * as providers_credentials from "../providers/credentials.js";
import type * as providers_data from "../providers/data.js";
import type * as providers_github_app from "../providers/github/app.js";
import type * as providers_github_config from "../providers/github/config.js";
import type * as providers_github_credentials from "../providers/github/credentials.js";
import type * as providers_github_events from "../providers/github/events.js";
import type * as providers_github_gate from "../providers/github/gate.js";
import type * as providers_github_http from "../providers/github/http.js";
import type * as providers_github_install from "../providers/github/install.js";
import type * as providers_github_signing from "../providers/github/signing.js";
import type * as providers_github_types from "../providers/github/types.js";
import type * as providers_google_config from "../providers/google/config.js";
import type * as providers_google_credentials from "../providers/google/credentials.js";
import type * as providers_google_data from "../providers/google/data.js";
import type * as providers_google_http from "../providers/google/http.js";
import type * as providers_google_install from "../providers/google/install.js";
import type * as providers_google_oauth from "../providers/google/oauth.js";
import type * as providers_google_scope from "../providers/google/scope.js";
import type * as providers_google_signing from "../providers/google/signing.js";
import type * as providers_http from "../providers/http.js";
import type * as providers_install from "../providers/install.js";
import type * as providers_linear_config from "../providers/linear/config.js";
import type * as providers_linear_credentials from "../providers/linear/credentials.js";
import type * as providers_linear_data from "../providers/linear/data.js";
import type * as providers_linear_events from "../providers/linear/events.js";
import type * as providers_linear_gate from "../providers/linear/gate.js";
import type * as providers_linear_graphql from "../providers/linear/graphql.js";
import type * as providers_linear_http from "../providers/linear/http.js";
import type * as providers_linear_hydration from "../providers/linear/hydration.js";
import type * as providers_linear_install from "../providers/linear/install.js";
import type * as providers_linear_issues from "../providers/linear/issues.js";
import type * as providers_linear_oauth from "../providers/linear/oauth.js";
import type * as providers_linear_signing from "../providers/linear/signing.js";
import type * as providers_microsoft_config from "../providers/microsoft/config.js";
import type * as providers_microsoft_credentials from "../providers/microsoft/credentials.js";
import type * as providers_microsoft_data from "../providers/microsoft/data.js";
import type * as providers_microsoft_http from "../providers/microsoft/http.js";
import type * as providers_microsoft_identity from "../providers/microsoft/identity.js";
import type * as providers_microsoft_install from "../providers/microsoft/install.js";
import type * as providers_microsoft_oauth from "../providers/microsoft/oauth.js";
import type * as providers_microsoft_signing from "../providers/microsoft/signing.js";
import type * as providers_notion_config from "../providers/notion/config.js";
import type * as providers_notion_credentials from "../providers/notion/credentials.js";
import type * as providers_notion_data from "../providers/notion/data.js";
import type * as providers_notion_events from "../providers/notion/events.js";
import type * as providers_notion_http from "../providers/notion/http.js";
import type * as providers_notion_install from "../providers/notion/install.js";
import type * as providers_notion_oauth from "../providers/notion/oauth.js";
import type * as providers_notion_pages from "../providers/notion/pages.js";
import type * as providers_notion_signing from "../providers/notion/signing.js";
import type * as providers_oauth from "../providers/oauth.js";
import type * as providers_signing from "../providers/signing.js";
import type * as providers_slack_channels from "../providers/slack/channels.js";
import type * as providers_slack_config from "../providers/slack/config.js";
import type * as providers_slack_credentials from "../providers/slack/credentials.js";
import type * as providers_slack_data from "../providers/slack/data.js";
import type * as providers_slack_events from "../providers/slack/events.js";
import type * as providers_slack_gate from "../providers/slack/gate.js";
import type * as providers_slack_http from "../providers/slack/http.js";
import type * as providers_slack_install from "../providers/slack/install.js";
import type * as providers_slack_links from "../providers/slack/links.js";
import type * as providers_slack_oauth from "../providers/slack/oauth.js";
import type * as providers_slack_signing from "../providers/slack/signing.js";
import type * as providers_slack_users from "../providers/slack/users.js";
import type * as runs_display from "../runs/display.js";
import type * as runs_snapshot from "../runs/snapshot.js";
import type * as shared_actor from "../shared/actor.js";
import type * as skills_catalog from "../skills/catalog.js";
import type * as skills_data from "../skills/data.js";
import type * as sources_metadata from "../sources/metadata.js";
import type * as subscriptions_data from "../subscriptions/data.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "activations/data": typeof activations_data;
  "approvals/approvals": typeof approvals_approvals;
  "approvals/console": typeof approvals_console;
  "approvals/runtime": typeof approvals_runtime;
  "approvals/slack/blocks": typeof approvals_slack_blocks;
  "approvals/slack/cards": typeof approvals_slack_cards;
  "approvals/slack/decision": typeof approvals_slack_decision;
  "approvals/slack/index": typeof approvals_slack_index;
  "approvals/slack/labels": typeof approvals_slack_labels;
  "approvals/summary": typeof approvals_summary;
  "artifacts/attachments": typeof artifacts_attachments;
  "artifacts/data": typeof artifacts_data;
  "artifacts/mcp": typeof artifacts_mcp;
  "automations/access": typeof automations_access;
  "automations/console": typeof automations_console;
  "automations/cron": typeof automations_cron;
  "automations/data": typeof automations_data;
  "automations/events": typeof automations_events;
  "automations/fire": typeof automations_fire;
  "automations/labels": typeof automations_labels;
  "automations/mcp": typeof automations_mcp;
  "automations/names": typeof automations_names;
  "automations/options": typeof automations_options;
  "automations/options/common": typeof automations_options_common;
  "automations/options/github": typeof automations_options_github;
  "automations/options/google": typeof automations_options_google;
  "automations/options/linear": typeof automations_options_linear;
  "automations/options/microsoft": typeof automations_options_microsoft;
  "automations/options/notion": typeof automations_options_notion;
  "automations/options/providers": typeof automations_options_providers;
  "automations/options/slack": typeof automations_options_slack;
  "automations/providers": typeof automations_providers;
  "automations/read": typeof automations_read;
  "automations/records": typeof automations_records;
  "automations/run": typeof automations_run;
  "automations/search": typeof automations_search;
  "automations/timing": typeof automations_timing;
  "automations/trigger": typeof automations_trigger;
  "automations/write": typeof automations_write;
  "broker/approval/args": typeof broker_approval_args;
  "broker/approval/index": typeof broker_approval_index;
  "broker/artifacts": typeof broker_artifacts;
  "broker/mcp": typeof broker_mcp;
  "broker/milo": typeof broker_milo;
  "broker/tools/common": typeof broker_tools_common;
  "broker/tools/fixtures/artifacts": typeof broker_tools_fixtures_artifacts;
  "broker/tools/github/client": typeof broker_tools_github_client;
  "broker/tools/github/comments": typeof broker_tools_github_comments;
  "broker/tools/github/format": typeof broker_tools_github_format;
  "broker/tools/github/index": typeof broker_tools_github_index;
  "broker/tools/google/drive/format": typeof broker_tools_google_drive_format;
  "broker/tools/google/drive/index": typeof broker_tools_google_drive_index;
  "broker/tools/google/format": typeof broker_tools_google_format;
  "broker/tools/google/gmail": typeof broker_tools_google_gmail;
  "broker/tools/google/index": typeof broker_tools_google_index;
  "broker/tools/google/request": typeof broker_tools_google_request;
  "broker/tools/index": typeof broker_tools_index;
  "broker/tools/linear": typeof broker_tools_linear;
  "broker/tools/microsoft": typeof broker_tools_microsoft;
  "broker/tools/notion": typeof broker_tools_notion;
  "broker/tools/slack/client": typeof broker_tools_slack_client;
  "broker/tools/slack/index": typeof broker_tools_slack_index;
  "broker/tools/slack/upload": typeof broker_tools_slack_upload;
  "events/data": typeof events_data;
  "events/ingest": typeof events_ingest;
  "executions/agent/artifacts": typeof executions_agent_artifacts;
  "executions/agent/authorization": typeof executions_agent_authorization;
  "executions/agent/codex": typeof executions_agent_codex;
  "executions/agent/data": typeof executions_agent_data;
  "executions/agent/prompt/continuation": typeof executions_agent_prompt_continuation;
  "executions/agent/prompt/fixtures": typeof executions_agent_prompt_fixtures;
  "executions/agent/prompt/index": typeof executions_agent_prompt_index;
  "executions/agent/prompt/instructions": typeof executions_agent_prompt_instructions;
  "executions/agent/prompt/integration": typeof executions_agent_prompt_integration;
  "executions/agent/sandbox/e2b": typeof executions_agent_sandbox_e2b;
  "executions/agent/sandbox/execute": typeof executions_agent_sandbox_execute;
  "executions/agent/sandbox/harness": typeof executions_agent_sandbox_harness;
  "executions/agent/sandbox/preflights/index": typeof executions_agent_sandbox_preflights_index;
  "executions/agent/sandbox/preflights/script": typeof executions_agent_sandbox_preflights_script;
  "executions/agent/sandbox/preflights/slack": typeof executions_agent_sandbox_preflights_slack;
  "executions/agent/sandbox/preflights/specs": typeof executions_agent_sandbox_preflights_specs;
  "executions/agent/sandbox/profile": typeof executions_agent_sandbox_profile;
  "executions/agent/sandbox/skills": typeof executions_agent_sandbox_skills;
  "executions/agent/sandbox/trace": typeof executions_agent_sandbox_trace;
  "executions/agent/targets": typeof executions_agent_targets;
  "executions/agent/tokens": typeof executions_agent_tokens;
  "executions/agent/tools/adapter": typeof executions_agent_tools_adapter;
  "executions/agent/tools/assemble": typeof executions_agent_tools_assemble;
  "executions/agent/tools/brokered": typeof executions_agent_tools_brokered;
  "executions/agent/tools/bundles": typeof executions_agent_tools_bundles;
  "executions/agent/tools/definitions": typeof executions_agent_tools_definitions;
  "executions/agent/tools/index": typeof executions_agent_tools_index;
  "executions/agent/tools/milo/bundle": typeof executions_agent_tools_milo_bundle;
  "executions/agent/tools/milo/index": typeof executions_agent_tools_milo_index;
  "executions/agent/tools/milo/script": typeof executions_agent_tools_milo_script;
  "executions/agent/tools/permissions/fixtures": typeof executions_agent_tools_permissions_fixtures;
  "executions/agent/tools/policy": typeof executions_agent_tools_policy;
  "executions/agent/tools/resolve": typeof executions_agent_tools_resolve;
  "executions/agent/tools/schemas/common": typeof executions_agent_tools_schemas_common;
  "executions/agent/tools/schemas/github": typeof executions_agent_tools_schemas_github;
  "executions/agent/tools/schemas/google": typeof executions_agent_tools_schemas_google;
  "executions/agent/tools/schemas/index": typeof executions_agent_tools_schemas_index;
  "executions/agent/tools/schemas/linear": typeof executions_agent_tools_schemas_linear;
  "executions/agent/tools/schemas/microsoft": typeof executions_agent_tools_schemas_microsoft;
  "executions/agent/tools/schemas/milo": typeof executions_agent_tools_schemas_milo;
  "executions/agent/tools/schemas/notion": typeof executions_agent_tools_schemas_notion;
  "executions/agent/tools/schemas/slack": typeof executions_agent_tools_schemas_slack;
  "executions/agent/tools/snapshot": typeof executions_agent_tools_snapshot;
  "executions/agent/tools/types": typeof executions_agent_tools_types;
  "executions/approvals": typeof executions_approvals;
  "executions/console": typeof executions_console;
  "executions/console/context": typeof executions_console_context;
  "executions/console/detail": typeof executions_console_detail;
  "executions/console/details/index": typeof executions_console_details_index;
  "executions/console/display/helpers": typeof executions_console_display_helpers;
  "executions/console/filters": typeof executions_console_filters;
  "executions/console/labels": typeof executions_console_labels;
  "executions/console/origin": typeof executions_console_origin;
  "executions/console/pending": typeof executions_console_pending;
  "executions/console/schedule": typeof executions_console_schedule;
  "executions/console/source": typeof executions_console_source;
  "executions/console/summaries/index": typeof executions_console_summaries_index;
  "executions/console/tools": typeof executions_console_tools;
  "executions/control": typeof executions_control;
  "executions/monitor": typeof executions_monitor;
  "executions/records": typeof executions_records;
  "executions/runtime": typeof executions_runtime;
  http: typeof http;
  "identity/access": typeof identity_access;
  "identity/clerk": typeof identity_clerk;
  "identity/clerk/data": typeof identity_clerk_data;
  "identity/clerk/profile": typeof identity_clerk_profile;
  "identity/identities": typeof identity_identities;
  "identity/organization": typeof identity_organization;
  "identity/users": typeof identity_users;
  "integrations/data": typeof integrations_data;
  "integrations/disconnect": typeof integrations_disconnect;
  "integrations/lookup": typeof integrations_lookup;
  "integrations/revoke": typeof integrations_revoke;
  "integrations/runtime": typeof integrations_runtime;
  "integrations/status": typeof integrations_status;
  "maintenance/truncate": typeof maintenance_truncate;
  "messages/events": typeof messages_events;
  "messages/ingest": typeof messages_ingest;
  "openrouter/client": typeof openrouter_client;
  "openrouter/index": typeof openrouter_index;
  "permissions/catalog": typeof permissions_catalog;
  "permissions/read": typeof permissions_read;
  "permissions/tools": typeof permissions_tools;
  "prompts/generated": typeof prompts_generated;
  "prompts/render": typeof prompts_render;
  "prompts/time": typeof prompts_time;
  "providers/catalog": typeof providers_catalog;
  "providers/credentials": typeof providers_credentials;
  "providers/data": typeof providers_data;
  "providers/github/app": typeof providers_github_app;
  "providers/github/config": typeof providers_github_config;
  "providers/github/credentials": typeof providers_github_credentials;
  "providers/github/events": typeof providers_github_events;
  "providers/github/gate": typeof providers_github_gate;
  "providers/github/http": typeof providers_github_http;
  "providers/github/install": typeof providers_github_install;
  "providers/github/signing": typeof providers_github_signing;
  "providers/github/types": typeof providers_github_types;
  "providers/google/config": typeof providers_google_config;
  "providers/google/credentials": typeof providers_google_credentials;
  "providers/google/data": typeof providers_google_data;
  "providers/google/http": typeof providers_google_http;
  "providers/google/install": typeof providers_google_install;
  "providers/google/oauth": typeof providers_google_oauth;
  "providers/google/scope": typeof providers_google_scope;
  "providers/google/signing": typeof providers_google_signing;
  "providers/http": typeof providers_http;
  "providers/install": typeof providers_install;
  "providers/linear/config": typeof providers_linear_config;
  "providers/linear/credentials": typeof providers_linear_credentials;
  "providers/linear/data": typeof providers_linear_data;
  "providers/linear/events": typeof providers_linear_events;
  "providers/linear/gate": typeof providers_linear_gate;
  "providers/linear/graphql": typeof providers_linear_graphql;
  "providers/linear/http": typeof providers_linear_http;
  "providers/linear/hydration": typeof providers_linear_hydration;
  "providers/linear/install": typeof providers_linear_install;
  "providers/linear/issues": typeof providers_linear_issues;
  "providers/linear/oauth": typeof providers_linear_oauth;
  "providers/linear/signing": typeof providers_linear_signing;
  "providers/microsoft/config": typeof providers_microsoft_config;
  "providers/microsoft/credentials": typeof providers_microsoft_credentials;
  "providers/microsoft/data": typeof providers_microsoft_data;
  "providers/microsoft/http": typeof providers_microsoft_http;
  "providers/microsoft/identity": typeof providers_microsoft_identity;
  "providers/microsoft/install": typeof providers_microsoft_install;
  "providers/microsoft/oauth": typeof providers_microsoft_oauth;
  "providers/microsoft/signing": typeof providers_microsoft_signing;
  "providers/notion/config": typeof providers_notion_config;
  "providers/notion/credentials": typeof providers_notion_credentials;
  "providers/notion/data": typeof providers_notion_data;
  "providers/notion/events": typeof providers_notion_events;
  "providers/notion/http": typeof providers_notion_http;
  "providers/notion/install": typeof providers_notion_install;
  "providers/notion/oauth": typeof providers_notion_oauth;
  "providers/notion/pages": typeof providers_notion_pages;
  "providers/notion/signing": typeof providers_notion_signing;
  "providers/oauth": typeof providers_oauth;
  "providers/signing": typeof providers_signing;
  "providers/slack/channels": typeof providers_slack_channels;
  "providers/slack/config": typeof providers_slack_config;
  "providers/slack/credentials": typeof providers_slack_credentials;
  "providers/slack/data": typeof providers_slack_data;
  "providers/slack/events": typeof providers_slack_events;
  "providers/slack/gate": typeof providers_slack_gate;
  "providers/slack/http": typeof providers_slack_http;
  "providers/slack/install": typeof providers_slack_install;
  "providers/slack/links": typeof providers_slack_links;
  "providers/slack/oauth": typeof providers_slack_oauth;
  "providers/slack/signing": typeof providers_slack_signing;
  "providers/slack/users": typeof providers_slack_users;
  "runs/display": typeof runs_display;
  "runs/snapshot": typeof runs_snapshot;
  "shared/actor": typeof shared_actor;
  "skills/catalog": typeof skills_catalog;
  "skills/data": typeof skills_data;
  "sources/metadata": typeof sources_metadata;
  "subscriptions/data": typeof subscriptions_data;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
