/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as approvals_approvals from "../approvals/approvals.js";
import type * as approvals_cancel from "../approvals/cancel.js";
import type * as approvals_cancellation from "../approvals/cancellation.js";
import type * as approvals_console from "../approvals/console.js";
import type * as approvals_execution from "../approvals/execution.js";
import type * as approvals_lifecycle from "../approvals/lifecycle.js";
import type * as approvals_queries from "../approvals/queries.js";
import type * as approvals_result from "../approvals/result.js";
import type * as approvals_runtime from "../approvals/runtime.js";
import type * as approvals_slack_blocks from "../approvals/slack/blocks.js";
import type * as approvals_slack_cards from "../approvals/slack/cards.js";
import type * as approvals_slack_index from "../approvals/slack/index.js";
import type * as approvals_slack_labels from "../approvals/slack/labels.js";
import type * as approvals_slack_surface from "../approvals/slack/surface.js";
import type * as approvals_summary from "../approvals/summary.js";
import type * as approvals_transition from "../approvals/transition.js";
import type * as artifacts_access from "../artifacts/access.js";
import type * as artifacts_actions from "../artifacts/actions.js";
import type * as artifacts_console from "../artifacts/console.js";
import type * as artifacts_contract_index from "../artifacts/contract/index.js";
import type * as artifacts_contract_json from "../artifacts/contract/json.js";
import type * as artifacts_mcp from "../artifacts/mcp.js";
import type * as artifacts_publish from "../artifacts/publish.js";
import type * as artifacts_queries from "../artifacts/queries.js";
import type * as artifacts_records from "../artifacts/records.js";
import type * as artifacts_runtime from "../artifacts/runtime.js";
import type * as artifacts_serve_frame from "../artifacts/serve/frame.js";
import type * as artifacts_serve_http from "../artifacts/serve/http.js";
import type * as artifacts_serve_session from "../artifacts/serve/session.js";
import type * as artifacts_serve_sessions from "../artifacts/serve/sessions.js";
import type * as artifacts_serve_urls from "../artifacts/serve/urls.js";
import type * as artifacts_source_build from "../artifacts/source/build.js";
import type * as artifacts_source_git from "../artifacts/source/git.js";
import type * as artifacts_source_index from "../artifacts/source/index.js";
import type * as artifacts_source_template from "../artifacts/source/template.js";
import type * as artifacts_state from "../artifacts/state.js";
import type * as artifacts_storage_gc from "../artifacts/storage/gc.js";
import type * as artifacts_storage_links from "../artifacts/storage/links.js";
import type * as artifacts_storage_objects from "../artifacts/storage/objects.js";
import type * as artifacts_storage_purge from "../artifacts/storage/purge.js";
import type * as artifacts_storage_validators from "../artifacts/storage/validators.js";
import type * as artifacts_tools_args from "../artifacts/tools/args.js";
import type * as artifacts_tools_broker from "../artifacts/tools/broker.js";
import type * as artifacts_tools_cache from "../artifacts/tools/cache.js";
import type * as artifacts_tools_diagnostics from "../artifacts/tools/diagnostics.js";
import type * as artifacts_tools_input from "../artifacts/tools/input.js";
import type * as artifacts_tools_platform from "../artifacts/tools/platform.js";
import type * as artifacts_tools_prompt from "../artifacts/tools/prompt.js";
import type * as attachments_data from "../attachments/data.js";
import type * as attachments_mcp from "../attachments/mcp.js";
import type * as attachments_read from "../attachments/read.js";
import type * as automations_access from "../automations/access.js";
import type * as automations_console from "../automations/console.js";
import type * as automations_events from "../automations/events.js";
import type * as automations_integrations from "../automations/integrations.js";
import type * as automations_lifecycle_control from "../automations/lifecycle/control.js";
import type * as automations_lifecycle_fire from "../automations/lifecycle/fire.js";
import type * as automations_lifecycle_index from "../automations/lifecycle/index.js";
import type * as automations_lifecycle_read from "../automations/lifecycle/read.js";
import type * as automations_lifecycle_run from "../automations/lifecycle/run.js";
import type * as automations_lifecycle_search from "../automations/lifecycle/search.js";
import type * as automations_lifecycle_trigger from "../automations/lifecycle/trigger.js";
import type * as automations_lifecycle_write from "../automations/lifecycle/write.js";
import type * as automations_mcp from "../automations/mcp.js";
import type * as automations_names from "../automations/names.js";
import type * as automations_options from "../automations/options.js";
import type * as automations_options_common from "../automations/options/common.js";
import type * as automations_options_github from "../automations/options/github.js";
import type * as automations_options_google from "../automations/options/google.js";
import type * as automations_options_integrations from "../automations/options/integrations.js";
import type * as automations_options_linear from "../automations/options/linear.js";
import type * as automations_options_microsoft from "../automations/options/microsoft.js";
import type * as automations_options_notion from "../automations/options/notion.js";
import type * as automations_options_slack from "../automations/options/slack.js";
import type * as automations_records from "../automations/records.js";
import type * as automations_schedule_cron from "../automations/schedule/cron.js";
import type * as automations_schedule_labels from "../automations/schedule/labels.js";
import type * as automations_schedule_timing from "../automations/schedule/timing.js";
import type * as automations_subscriptions_data from "../automations/subscriptions/data.js";
import type * as broker_approval_args from "../broker/approval/args.js";
import type * as broker_approval_delivery from "../broker/approval/delivery.js";
import type * as broker_approval_index from "../broker/approval/index.js";
import type * as broker_attachments from "../broker/attachments.js";
import type * as broker_auth from "../broker/auth.js";
import type * as broker_capabilities from "../broker/capabilities.js";
import type * as broker_input from "../broker/input.js";
import type * as broker_mcp from "../broker/mcp.js";
import type * as broker_milo from "../broker/milo.js";
import type * as broker_tools_context from "../broker/tools/context.js";
import type * as broker_tools_fixtures from "../broker/tools/fixtures.js";
import type * as broker_tools_github_client from "../broker/tools/github/client.js";
import type * as broker_tools_github_comments from "../broker/tools/github/comments.js";
import type * as broker_tools_github_format from "../broker/tools/github/format.js";
import type * as broker_tools_github_index from "../broker/tools/github/index.js";
import type * as broker_tools_google_drive from "../broker/tools/google/drive.js";
import type * as broker_tools_google_format from "../broker/tools/google/format.js";
import type * as broker_tools_google_gmail from "../broker/tools/google/gmail.js";
import type * as broker_tools_google_index from "../broker/tools/google/index.js";
import type * as broker_tools_google_read from "../broker/tools/google/read.js";
import type * as broker_tools_index from "../broker/tools/index.js";
import type * as broker_tools_linear_client from "../broker/tools/linear/client.js";
import type * as broker_tools_linear_comments from "../broker/tools/linear/comments.js";
import type * as broker_tools_linear_index from "../broker/tools/linear/index.js";
import type * as broker_tools_linear_reactions from "../broker/tools/linear/reactions.js";
import type * as broker_tools_microsoft from "../broker/tools/microsoft.js";
import type * as broker_tools_notion_index from "../broker/tools/notion/index.js";
import type * as broker_tools_notion_upload from "../broker/tools/notion/upload.js";
import type * as broker_tools_slack_index from "../broker/tools/slack/index.js";
import type * as broker_tools_slack_upload from "../broker/tools/slack/upload.js";
import type * as broker_tools_web_index from "../broker/tools/web/index.js";
import type * as broker_tools_web_input from "../broker/tools/web/input.js";
import type * as broker_tools_web_output from "../broker/tools/web/output.js";
import type * as events_data from "../events/data.js";
import type * as events_ingest from "../events/ingest.js";
import type * as events_payload from "../events/payload.js";
import type * as http from "../http.js";
import type * as identity_access from "../identity/access.js";
import type * as identity_clerk from "../identity/clerk.js";
import type * as identity_clerk_data from "../identity/clerk/data.js";
import type * as identity_clerk_profile from "../identity/clerk/profile.js";
import type * as identity_identities from "../identity/identities.js";
import type * as identity_organization from "../identity/organization.js";
import type * as identity_users from "../identity/users.js";
import type * as integrations_catalog from "../integrations/catalog.js";
import type * as integrations_data from "../integrations/data.js";
import type * as integrations_disconnect from "../integrations/disconnect.js";
import type * as integrations_lookup from "../integrations/lookup.js";
import type * as integrations_offers_delivery from "../integrations/offers/delivery.js";
import type * as integrations_offers_helpers from "../integrations/offers/helpers.js";
import type * as integrations_offers_interaction from "../integrations/offers/interaction.js";
import type * as integrations_offers_lifecycle from "../integrations/offers/lifecycle.js";
import type * as integrations_offers_mcp from "../integrations/offers/mcp.js";
import type * as integrations_offers_records from "../integrations/offers/records.js";
import type * as integrations_offers_slack from "../integrations/offers/slack.js";
import type * as integrations_offers_source from "../integrations/offers/source.js";
import type * as integrations_offers_tokens from "../integrations/offers/tokens.js";
import type * as integrations_offers_transition from "../integrations/offers/transition.js";
import type * as integrations_offers_updates from "../integrations/offers/updates.js";
import type * as integrations_revoke from "../integrations/revoke.js";
import type * as integrations_runtime from "../integrations/runtime.js";
import type * as integrations_status from "../integrations/status.js";
import type * as maintenance from "../maintenance.js";
import type * as messages_data from "../messages/data.js";
import type * as messages_events from "../messages/events.js";
import type * as messages_history from "../messages/history.js";
import type * as messages_identifiers from "../messages/identifiers.js";
import type * as messages_intake from "../messages/intake.js";
import type * as messages_surface from "../messages/surface.js";
import type * as messages_targets from "../messages/targets.js";
import type * as model_index from "../model/index.js";
import type * as model_openrouter from "../model/openrouter.js";
import type * as permissions_catalog from "../permissions/catalog.js";
import type * as permissions_read from "../permissions/read.js";
import type * as permissions_tools from "../permissions/tools.js";
import type * as prompts_generated from "../prompts/generated.js";
import type * as prompts_render from "../prompts/render.js";
import type * as prompts_time from "../prompts/time.js";
import type * as providers_catalog from "../providers/catalog.js";
import type * as providers_credentials from "../providers/credentials.js";
import type * as providers_data from "../providers/data.js";
import type * as providers_github_app from "../providers/github/app.js";
import type * as providers_github_config from "../providers/github/config.js";
import type * as providers_github_credentials from "../providers/github/credentials.js";
import type * as providers_github_events from "../providers/github/events.js";
import type * as providers_github_http from "../providers/github/http.js";
import type * as providers_github_install from "../providers/github/install.js";
import type * as providers_github_signing from "../providers/github/signing.js";
import type * as providers_github_types from "../providers/github/types.js";
import type * as providers_google_api from "../providers/google/api.js";
import type * as providers_google_config from "../providers/google/config.js";
import type * as providers_google_credentials from "../providers/google/credentials.js";
import type * as providers_google_data from "../providers/google/data.js";
import type * as providers_google_drive from "../providers/google/drive.js";
import type * as providers_google_http from "../providers/google/http.js";
import type * as providers_google_install from "../providers/google/install.js";
import type * as providers_google_oauth from "../providers/google/oauth.js";
import type * as providers_google_scope from "../providers/google/scope.js";
import type * as providers_google_signing from "../providers/google/signing.js";
import type * as providers_http from "../providers/http.js";
import type * as providers_install from "../providers/install.js";
import type * as providers_linear_approvals from "../providers/linear/approvals.js";
import type * as providers_linear_config from "../providers/linear/config.js";
import type * as providers_linear_credentials from "../providers/linear/credentials.js";
import type * as providers_linear_data from "../providers/linear/data.js";
import type * as providers_linear_events from "../providers/linear/events.js";
import type * as providers_linear_graphql from "../providers/linear/graphql.js";
import type * as providers_linear_http from "../providers/linear/http.js";
import type * as providers_linear_hydration from "../providers/linear/hydration.js";
import type * as providers_linear_install from "../providers/linear/install.js";
import type * as providers_linear_issues from "../providers/linear/issues.js";
import type * as providers_linear_oauth from "../providers/linear/oauth.js";
import type * as providers_linear_signing from "../providers/linear/signing.js";
import type * as providers_microsoft_config from "../providers/microsoft/config.js";
import type * as providers_microsoft_credentials from "../providers/microsoft/credentials.js";
import type * as providers_microsoft_data from "../providers/microsoft/data.js";
import type * as providers_microsoft_http from "../providers/microsoft/http.js";
import type * as providers_microsoft_identity from "../providers/microsoft/identity.js";
import type * as providers_microsoft_install from "../providers/microsoft/install.js";
import type * as providers_microsoft_oauth from "../providers/microsoft/oauth.js";
import type * as providers_microsoft_signing from "../providers/microsoft/signing.js";
import type * as providers_notion_api from "../providers/notion/api.js";
import type * as providers_notion_config from "../providers/notion/config.js";
import type * as providers_notion_credentials from "../providers/notion/credentials.js";
import type * as providers_notion_data from "../providers/notion/data.js";
import type * as providers_notion_events from "../providers/notion/events.js";
import type * as providers_notion_http from "../providers/notion/http.js";
import type * as providers_notion_install from "../providers/notion/install.js";
import type * as providers_notion_oauth from "../providers/notion/oauth.js";
import type * as providers_notion_pages from "../providers/notion/pages.js";
import type * as providers_notion_signing from "../providers/notion/signing.js";
import type * as providers_oauth from "../providers/oauth.js";
import type * as providers_signing from "../providers/signing.js";
import type * as providers_slack_api from "../providers/slack/api.js";
import type * as providers_slack_card from "../providers/slack/card.js";
import type * as providers_slack_config from "../providers/slack/config.js";
import type * as providers_slack_credentials from "../providers/slack/credentials.js";
import type * as providers_slack_data from "../providers/slack/data.js";
import type * as providers_slack_directory_channels from "../providers/slack/directory/channels.js";
import type * as providers_slack_directory_users from "../providers/slack/directory/users.js";
import type * as providers_slack_events from "../providers/slack/events.js";
import type * as providers_slack_format from "../providers/slack/format.js";
import type * as providers_slack_http from "../providers/slack/http.js";
import type * as providers_slack_install from "../providers/slack/install.js";
import type * as providers_slack_links from "../providers/slack/links.js";
import type * as providers_slack_oauth from "../providers/slack/oauth.js";
import type * as providers_slack_signing from "../providers/slack/signing.js";
import type * as runs_agent_authorization from "../runs/agent/authorization.js";
import type * as runs_agent_input from "../runs/agent/input.js";
import type * as runs_agent_prompt_communication from "../runs/agent/prompt/communication.js";
import type * as runs_agent_prompt_conversation from "../runs/agent/prompt/conversation.js";
import type * as runs_agent_prompt_fixtures from "../runs/agent/prompt/fixtures.js";
import type * as runs_agent_prompt_index from "../runs/agent/prompt/index.js";
import type * as runs_agent_prompt_instructions from "../runs/agent/prompt/instructions.js";
import type * as runs_agent_prompt_integration from "../runs/agent/prompt/integration.js";
import type * as runs_agent_prompt_skills from "../runs/agent/prompt/skills.js";
import type * as runs_agent_prompt_target from "../runs/agent/prompt/target.js";
import type * as runs_agent_targets from "../runs/agent/targets.js";
import type * as runs_agent_tools_bundles from "../runs/agent/tools/bundles.js";
import type * as runs_agent_tools_definitions from "../runs/agent/tools/definitions.js";
import type * as runs_agent_tools_fixtures from "../runs/agent/tools/fixtures.js";
import type * as runs_agent_tools_index from "../runs/agent/tools/index.js";
import type * as runs_agent_tools_policy from "../runs/agent/tools/policy.js";
import type * as runs_agent_tools_resolve from "../runs/agent/tools/resolve.js";
import type * as runs_agent_tools_schemas_artifacts from "../runs/agent/tools/schemas/artifacts.js";
import type * as runs_agent_tools_schemas_calendar from "../runs/agent/tools/schemas/calendar.js";
import type * as runs_agent_tools_schemas_common from "../runs/agent/tools/schemas/common.js";
import type * as runs_agent_tools_schemas_github from "../runs/agent/tools/schemas/github.js";
import type * as runs_agent_tools_schemas_google from "../runs/agent/tools/schemas/google.js";
import type * as runs_agent_tools_schemas_index from "../runs/agent/tools/schemas/index.js";
import type * as runs_agent_tools_schemas_linear from "../runs/agent/tools/schemas/linear.js";
import type * as runs_agent_tools_schemas_microsoft from "../runs/agent/tools/schemas/microsoft.js";
import type * as runs_agent_tools_schemas_milo_automations from "../runs/agent/tools/schemas/milo/automations.js";
import type * as runs_agent_tools_schemas_milo_core from "../runs/agent/tools/schemas/milo/core.js";
import type * as runs_agent_tools_schemas_milo_index from "../runs/agent/tools/schemas/milo/index.js";
import type * as runs_agent_tools_schemas_notion_index from "../runs/agent/tools/schemas/notion/index.js";
import type * as runs_agent_tools_schemas_notion_media from "../runs/agent/tools/schemas/notion/media.js";
import type * as runs_agent_tools_schemas_slack from "../runs/agent/tools/schemas/slack.js";
import type * as runs_agent_tools_snapshot from "../runs/agent/tools/snapshot.js";
import type * as runs_agent_tools_types from "../runs/agent/tools/types.js";
import type * as runs_console from "../runs/console.js";
import type * as runs_console_context from "../runs/console/context.js";
import type * as runs_console_details from "../runs/console/details.js";
import type * as runs_console_display from "../runs/console/display.js";
import type * as runs_console_filters from "../runs/console/filters.js";
import type * as runs_console_labels from "../runs/console/labels.js";
import type * as runs_console_pending from "../runs/console/pending.js";
import type * as runs_console_source from "../runs/console/source.js";
import type * as runs_console_summaries from "../runs/console/summaries.js";
import type * as runs_console_tools from "../runs/console/tools.js";
import type * as runs_control from "../runs/control.js";
import type * as runs_display_detail from "../runs/display/detail.js";
import type * as runs_display_index from "../runs/display/index.js";
import type * as runs_display_metadata from "../runs/display/metadata.js";
import type * as runs_display_origin from "../runs/display/origin.js";
import type * as runs_display_schedule from "../runs/display/schedule.js";
import type * as runs_monitor from "../runs/monitor.js";
import type * as runs_records from "../runs/records.js";
import type * as runs_snapshot from "../runs/snapshot.js";
import type * as runtime__generated_assets from "../runtime/_generated/assets.js";
import type * as runtime_children from "../runtime/children.js";
import type * as runtime_context from "../runtime/context.js";
import type * as runtime_dispatch from "../runtime/dispatch.js";
import type * as runtime_lifecycle_snapshot from "../runtime/lifecycle/snapshot.js";
import type * as runtime_lifecycle_tools from "../runtime/lifecycle/tools.js";
import type * as runtime_outbox from "../runtime/outbox.js";
import type * as runtime_permissions_index from "../runtime/permissions/index.js";
import type * as runtime_permissions_tools from "../runtime/permissions/tools.js";
import type * as runtime_sandbox from "../runtime/sandbox.js";
import type * as runtime_sandboxes from "../runtime/sandboxes.js";
import type * as runtime_sessions from "../runtime/sessions.js";
import type * as runtime_shared from "../runtime/shared.js";
import type * as runtime_surface from "../runtime/surface.js";
import type * as runtime_surface_reply from "../runtime/surface/reply.js";
import type * as runtime_surface_tools from "../runtime/surface/tools.js";
import type * as runtime_tools from "../runtime/tools.js";
import type * as runtime_traces from "../runtime/traces.js";
import type * as runtime_waiters_data from "../runtime/waiters/data.js";
import type * as runtime_waiters_handoffs from "../runtime/waiters/handoffs.js";
import type * as sessions_cursor from "../sessions/cursor.js";
import type * as sessions_data from "../sessions/data.js";
import type * as shared_actor from "../shared/actor.js";
import type * as shared_app from "../shared/app.js";
import type * as shared_data from "../shared/data.js";
import type * as shared_encoding from "../shared/encoding.js";
import type * as shared_http from "../shared/http.js";
import type * as shared_input from "../shared/input.js";
import type * as shared_integrations from "../shared/integrations.js";
import type * as skills_catalog from "../skills/catalog.js";
import type * as skills_communication from "../skills/communication.js";
import type * as skills_data from "../skills/data.js";
import type * as skills_mcp from "../skills/mcp.js";
import type * as skills_runtime from "../skills/runtime.js";
import type * as transitions from "../transitions.js";
import type * as watches_continuation from "../watches/continuation.js";
import type * as watches_data from "../watches/data.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "approvals/approvals": typeof approvals_approvals;
  "approvals/cancel": typeof approvals_cancel;
  "approvals/cancellation": typeof approvals_cancellation;
  "approvals/console": typeof approvals_console;
  "approvals/execution": typeof approvals_execution;
  "approvals/lifecycle": typeof approvals_lifecycle;
  "approvals/queries": typeof approvals_queries;
  "approvals/result": typeof approvals_result;
  "approvals/runtime": typeof approvals_runtime;
  "approvals/slack/blocks": typeof approvals_slack_blocks;
  "approvals/slack/cards": typeof approvals_slack_cards;
  "approvals/slack/index": typeof approvals_slack_index;
  "approvals/slack/labels": typeof approvals_slack_labels;
  "approvals/slack/surface": typeof approvals_slack_surface;
  "approvals/summary": typeof approvals_summary;
  "approvals/transition": typeof approvals_transition;
  "artifacts/access": typeof artifacts_access;
  "artifacts/actions": typeof artifacts_actions;
  "artifacts/console": typeof artifacts_console;
  "artifacts/contract/index": typeof artifacts_contract_index;
  "artifacts/contract/json": typeof artifacts_contract_json;
  "artifacts/mcp": typeof artifacts_mcp;
  "artifacts/publish": typeof artifacts_publish;
  "artifacts/queries": typeof artifacts_queries;
  "artifacts/records": typeof artifacts_records;
  "artifacts/runtime": typeof artifacts_runtime;
  "artifacts/serve/frame": typeof artifacts_serve_frame;
  "artifacts/serve/http": typeof artifacts_serve_http;
  "artifacts/serve/session": typeof artifacts_serve_session;
  "artifacts/serve/sessions": typeof artifacts_serve_sessions;
  "artifacts/serve/urls": typeof artifacts_serve_urls;
  "artifacts/source/build": typeof artifacts_source_build;
  "artifacts/source/git": typeof artifacts_source_git;
  "artifacts/source/index": typeof artifacts_source_index;
  "artifacts/source/template": typeof artifacts_source_template;
  "artifacts/state": typeof artifacts_state;
  "artifacts/storage/gc": typeof artifacts_storage_gc;
  "artifacts/storage/links": typeof artifacts_storage_links;
  "artifacts/storage/objects": typeof artifacts_storage_objects;
  "artifacts/storage/purge": typeof artifacts_storage_purge;
  "artifacts/storage/validators": typeof artifacts_storage_validators;
  "artifacts/tools/args": typeof artifacts_tools_args;
  "artifacts/tools/broker": typeof artifacts_tools_broker;
  "artifacts/tools/cache": typeof artifacts_tools_cache;
  "artifacts/tools/diagnostics": typeof artifacts_tools_diagnostics;
  "artifacts/tools/input": typeof artifacts_tools_input;
  "artifacts/tools/platform": typeof artifacts_tools_platform;
  "artifacts/tools/prompt": typeof artifacts_tools_prompt;
  "attachments/data": typeof attachments_data;
  "attachments/mcp": typeof attachments_mcp;
  "attachments/read": typeof attachments_read;
  "automations/access": typeof automations_access;
  "automations/console": typeof automations_console;
  "automations/events": typeof automations_events;
  "automations/integrations": typeof automations_integrations;
  "automations/lifecycle/control": typeof automations_lifecycle_control;
  "automations/lifecycle/fire": typeof automations_lifecycle_fire;
  "automations/lifecycle/index": typeof automations_lifecycle_index;
  "automations/lifecycle/read": typeof automations_lifecycle_read;
  "automations/lifecycle/run": typeof automations_lifecycle_run;
  "automations/lifecycle/search": typeof automations_lifecycle_search;
  "automations/lifecycle/trigger": typeof automations_lifecycle_trigger;
  "automations/lifecycle/write": typeof automations_lifecycle_write;
  "automations/mcp": typeof automations_mcp;
  "automations/names": typeof automations_names;
  "automations/options": typeof automations_options;
  "automations/options/common": typeof automations_options_common;
  "automations/options/github": typeof automations_options_github;
  "automations/options/google": typeof automations_options_google;
  "automations/options/integrations": typeof automations_options_integrations;
  "automations/options/linear": typeof automations_options_linear;
  "automations/options/microsoft": typeof automations_options_microsoft;
  "automations/options/notion": typeof automations_options_notion;
  "automations/options/slack": typeof automations_options_slack;
  "automations/records": typeof automations_records;
  "automations/schedule/cron": typeof automations_schedule_cron;
  "automations/schedule/labels": typeof automations_schedule_labels;
  "automations/schedule/timing": typeof automations_schedule_timing;
  "automations/subscriptions/data": typeof automations_subscriptions_data;
  "broker/approval/args": typeof broker_approval_args;
  "broker/approval/delivery": typeof broker_approval_delivery;
  "broker/approval/index": typeof broker_approval_index;
  "broker/attachments": typeof broker_attachments;
  "broker/auth": typeof broker_auth;
  "broker/capabilities": typeof broker_capabilities;
  "broker/input": typeof broker_input;
  "broker/mcp": typeof broker_mcp;
  "broker/milo": typeof broker_milo;
  "broker/tools/context": typeof broker_tools_context;
  "broker/tools/fixtures": typeof broker_tools_fixtures;
  "broker/tools/github/client": typeof broker_tools_github_client;
  "broker/tools/github/comments": typeof broker_tools_github_comments;
  "broker/tools/github/format": typeof broker_tools_github_format;
  "broker/tools/github/index": typeof broker_tools_github_index;
  "broker/tools/google/drive": typeof broker_tools_google_drive;
  "broker/tools/google/format": typeof broker_tools_google_format;
  "broker/tools/google/gmail": typeof broker_tools_google_gmail;
  "broker/tools/google/index": typeof broker_tools_google_index;
  "broker/tools/google/read": typeof broker_tools_google_read;
  "broker/tools/index": typeof broker_tools_index;
  "broker/tools/linear/client": typeof broker_tools_linear_client;
  "broker/tools/linear/comments": typeof broker_tools_linear_comments;
  "broker/tools/linear/index": typeof broker_tools_linear_index;
  "broker/tools/linear/reactions": typeof broker_tools_linear_reactions;
  "broker/tools/microsoft": typeof broker_tools_microsoft;
  "broker/tools/notion/index": typeof broker_tools_notion_index;
  "broker/tools/notion/upload": typeof broker_tools_notion_upload;
  "broker/tools/slack/index": typeof broker_tools_slack_index;
  "broker/tools/slack/upload": typeof broker_tools_slack_upload;
  "broker/tools/web/index": typeof broker_tools_web_index;
  "broker/tools/web/input": typeof broker_tools_web_input;
  "broker/tools/web/output": typeof broker_tools_web_output;
  "events/data": typeof events_data;
  "events/ingest": typeof events_ingest;
  "events/payload": typeof events_payload;
  http: typeof http;
  "identity/access": typeof identity_access;
  "identity/clerk": typeof identity_clerk;
  "identity/clerk/data": typeof identity_clerk_data;
  "identity/clerk/profile": typeof identity_clerk_profile;
  "identity/identities": typeof identity_identities;
  "identity/organization": typeof identity_organization;
  "identity/users": typeof identity_users;
  "integrations/catalog": typeof integrations_catalog;
  "integrations/data": typeof integrations_data;
  "integrations/disconnect": typeof integrations_disconnect;
  "integrations/lookup": typeof integrations_lookup;
  "integrations/offers/delivery": typeof integrations_offers_delivery;
  "integrations/offers/helpers": typeof integrations_offers_helpers;
  "integrations/offers/interaction": typeof integrations_offers_interaction;
  "integrations/offers/lifecycle": typeof integrations_offers_lifecycle;
  "integrations/offers/mcp": typeof integrations_offers_mcp;
  "integrations/offers/records": typeof integrations_offers_records;
  "integrations/offers/slack": typeof integrations_offers_slack;
  "integrations/offers/source": typeof integrations_offers_source;
  "integrations/offers/tokens": typeof integrations_offers_tokens;
  "integrations/offers/transition": typeof integrations_offers_transition;
  "integrations/offers/updates": typeof integrations_offers_updates;
  "integrations/revoke": typeof integrations_revoke;
  "integrations/runtime": typeof integrations_runtime;
  "integrations/status": typeof integrations_status;
  maintenance: typeof maintenance;
  "messages/data": typeof messages_data;
  "messages/events": typeof messages_events;
  "messages/history": typeof messages_history;
  "messages/identifiers": typeof messages_identifiers;
  "messages/intake": typeof messages_intake;
  "messages/surface": typeof messages_surface;
  "messages/targets": typeof messages_targets;
  "model/index": typeof model_index;
  "model/openrouter": typeof model_openrouter;
  "permissions/catalog": typeof permissions_catalog;
  "permissions/read": typeof permissions_read;
  "permissions/tools": typeof permissions_tools;
  "prompts/generated": typeof prompts_generated;
  "prompts/render": typeof prompts_render;
  "prompts/time": typeof prompts_time;
  "providers/catalog": typeof providers_catalog;
  "providers/credentials": typeof providers_credentials;
  "providers/data": typeof providers_data;
  "providers/github/app": typeof providers_github_app;
  "providers/github/config": typeof providers_github_config;
  "providers/github/credentials": typeof providers_github_credentials;
  "providers/github/events": typeof providers_github_events;
  "providers/github/http": typeof providers_github_http;
  "providers/github/install": typeof providers_github_install;
  "providers/github/signing": typeof providers_github_signing;
  "providers/github/types": typeof providers_github_types;
  "providers/google/api": typeof providers_google_api;
  "providers/google/config": typeof providers_google_config;
  "providers/google/credentials": typeof providers_google_credentials;
  "providers/google/data": typeof providers_google_data;
  "providers/google/drive": typeof providers_google_drive;
  "providers/google/http": typeof providers_google_http;
  "providers/google/install": typeof providers_google_install;
  "providers/google/oauth": typeof providers_google_oauth;
  "providers/google/scope": typeof providers_google_scope;
  "providers/google/signing": typeof providers_google_signing;
  "providers/http": typeof providers_http;
  "providers/install": typeof providers_install;
  "providers/linear/approvals": typeof providers_linear_approvals;
  "providers/linear/config": typeof providers_linear_config;
  "providers/linear/credentials": typeof providers_linear_credentials;
  "providers/linear/data": typeof providers_linear_data;
  "providers/linear/events": typeof providers_linear_events;
  "providers/linear/graphql": typeof providers_linear_graphql;
  "providers/linear/http": typeof providers_linear_http;
  "providers/linear/hydration": typeof providers_linear_hydration;
  "providers/linear/install": typeof providers_linear_install;
  "providers/linear/issues": typeof providers_linear_issues;
  "providers/linear/oauth": typeof providers_linear_oauth;
  "providers/linear/signing": typeof providers_linear_signing;
  "providers/microsoft/config": typeof providers_microsoft_config;
  "providers/microsoft/credentials": typeof providers_microsoft_credentials;
  "providers/microsoft/data": typeof providers_microsoft_data;
  "providers/microsoft/http": typeof providers_microsoft_http;
  "providers/microsoft/identity": typeof providers_microsoft_identity;
  "providers/microsoft/install": typeof providers_microsoft_install;
  "providers/microsoft/oauth": typeof providers_microsoft_oauth;
  "providers/microsoft/signing": typeof providers_microsoft_signing;
  "providers/notion/api": typeof providers_notion_api;
  "providers/notion/config": typeof providers_notion_config;
  "providers/notion/credentials": typeof providers_notion_credentials;
  "providers/notion/data": typeof providers_notion_data;
  "providers/notion/events": typeof providers_notion_events;
  "providers/notion/http": typeof providers_notion_http;
  "providers/notion/install": typeof providers_notion_install;
  "providers/notion/oauth": typeof providers_notion_oauth;
  "providers/notion/pages": typeof providers_notion_pages;
  "providers/notion/signing": typeof providers_notion_signing;
  "providers/oauth": typeof providers_oauth;
  "providers/signing": typeof providers_signing;
  "providers/slack/api": typeof providers_slack_api;
  "providers/slack/card": typeof providers_slack_card;
  "providers/slack/config": typeof providers_slack_config;
  "providers/slack/credentials": typeof providers_slack_credentials;
  "providers/slack/data": typeof providers_slack_data;
  "providers/slack/directory/channels": typeof providers_slack_directory_channels;
  "providers/slack/directory/users": typeof providers_slack_directory_users;
  "providers/slack/events": typeof providers_slack_events;
  "providers/slack/format": typeof providers_slack_format;
  "providers/slack/http": typeof providers_slack_http;
  "providers/slack/install": typeof providers_slack_install;
  "providers/slack/links": typeof providers_slack_links;
  "providers/slack/oauth": typeof providers_slack_oauth;
  "providers/slack/signing": typeof providers_slack_signing;
  "runs/agent/authorization": typeof runs_agent_authorization;
  "runs/agent/input": typeof runs_agent_input;
  "runs/agent/prompt/communication": typeof runs_agent_prompt_communication;
  "runs/agent/prompt/conversation": typeof runs_agent_prompt_conversation;
  "runs/agent/prompt/fixtures": typeof runs_agent_prompt_fixtures;
  "runs/agent/prompt/index": typeof runs_agent_prompt_index;
  "runs/agent/prompt/instructions": typeof runs_agent_prompt_instructions;
  "runs/agent/prompt/integration": typeof runs_agent_prompt_integration;
  "runs/agent/prompt/skills": typeof runs_agent_prompt_skills;
  "runs/agent/prompt/target": typeof runs_agent_prompt_target;
  "runs/agent/targets": typeof runs_agent_targets;
  "runs/agent/tools/bundles": typeof runs_agent_tools_bundles;
  "runs/agent/tools/definitions": typeof runs_agent_tools_definitions;
  "runs/agent/tools/fixtures": typeof runs_agent_tools_fixtures;
  "runs/agent/tools/index": typeof runs_agent_tools_index;
  "runs/agent/tools/policy": typeof runs_agent_tools_policy;
  "runs/agent/tools/resolve": typeof runs_agent_tools_resolve;
  "runs/agent/tools/schemas/artifacts": typeof runs_agent_tools_schemas_artifacts;
  "runs/agent/tools/schemas/calendar": typeof runs_agent_tools_schemas_calendar;
  "runs/agent/tools/schemas/common": typeof runs_agent_tools_schemas_common;
  "runs/agent/tools/schemas/github": typeof runs_agent_tools_schemas_github;
  "runs/agent/tools/schemas/google": typeof runs_agent_tools_schemas_google;
  "runs/agent/tools/schemas/index": typeof runs_agent_tools_schemas_index;
  "runs/agent/tools/schemas/linear": typeof runs_agent_tools_schemas_linear;
  "runs/agent/tools/schemas/microsoft": typeof runs_agent_tools_schemas_microsoft;
  "runs/agent/tools/schemas/milo/automations": typeof runs_agent_tools_schemas_milo_automations;
  "runs/agent/tools/schemas/milo/core": typeof runs_agent_tools_schemas_milo_core;
  "runs/agent/tools/schemas/milo/index": typeof runs_agent_tools_schemas_milo_index;
  "runs/agent/tools/schemas/notion/index": typeof runs_agent_tools_schemas_notion_index;
  "runs/agent/tools/schemas/notion/media": typeof runs_agent_tools_schemas_notion_media;
  "runs/agent/tools/schemas/slack": typeof runs_agent_tools_schemas_slack;
  "runs/agent/tools/snapshot": typeof runs_agent_tools_snapshot;
  "runs/agent/tools/types": typeof runs_agent_tools_types;
  "runs/console": typeof runs_console;
  "runs/console/context": typeof runs_console_context;
  "runs/console/details": typeof runs_console_details;
  "runs/console/display": typeof runs_console_display;
  "runs/console/filters": typeof runs_console_filters;
  "runs/console/labels": typeof runs_console_labels;
  "runs/console/pending": typeof runs_console_pending;
  "runs/console/source": typeof runs_console_source;
  "runs/console/summaries": typeof runs_console_summaries;
  "runs/console/tools": typeof runs_console_tools;
  "runs/control": typeof runs_control;
  "runs/display/detail": typeof runs_display_detail;
  "runs/display/index": typeof runs_display_index;
  "runs/display/metadata": typeof runs_display_metadata;
  "runs/display/origin": typeof runs_display_origin;
  "runs/display/schedule": typeof runs_display_schedule;
  "runs/monitor": typeof runs_monitor;
  "runs/records": typeof runs_records;
  "runs/snapshot": typeof runs_snapshot;
  "runtime/_generated/assets": typeof runtime__generated_assets;
  "runtime/children": typeof runtime_children;
  "runtime/context": typeof runtime_context;
  "runtime/dispatch": typeof runtime_dispatch;
  "runtime/lifecycle/snapshot": typeof runtime_lifecycle_snapshot;
  "runtime/lifecycle/tools": typeof runtime_lifecycle_tools;
  "runtime/outbox": typeof runtime_outbox;
  "runtime/permissions/index": typeof runtime_permissions_index;
  "runtime/permissions/tools": typeof runtime_permissions_tools;
  "runtime/sandbox": typeof runtime_sandbox;
  "runtime/sandboxes": typeof runtime_sandboxes;
  "runtime/sessions": typeof runtime_sessions;
  "runtime/shared": typeof runtime_shared;
  "runtime/surface": typeof runtime_surface;
  "runtime/surface/reply": typeof runtime_surface_reply;
  "runtime/surface/tools": typeof runtime_surface_tools;
  "runtime/tools": typeof runtime_tools;
  "runtime/traces": typeof runtime_traces;
  "runtime/waiters/data": typeof runtime_waiters_data;
  "runtime/waiters/handoffs": typeof runtime_waiters_handoffs;
  "sessions/cursor": typeof sessions_cursor;
  "sessions/data": typeof sessions_data;
  "shared/actor": typeof shared_actor;
  "shared/app": typeof shared_app;
  "shared/data": typeof shared_data;
  "shared/encoding": typeof shared_encoding;
  "shared/http": typeof shared_http;
  "shared/input": typeof shared_input;
  "shared/integrations": typeof shared_integrations;
  "skills/catalog": typeof skills_catalog;
  "skills/communication": typeof skills_communication;
  "skills/data": typeof skills_data;
  "skills/mcp": typeof skills_mcp;
  "skills/runtime": typeof skills_runtime;
  transitions: typeof transitions;
  "watches/continuation": typeof watches_continuation;
  "watches/data": typeof watches_data;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
