import { type ToolPermissionRow } from "./catalog"
import { githubToolPermissionRows } from "./github"
import { notionToolPermissionRows } from "./notion"

export const toolPermissionRows = [
  [
    "milo",
    "search_schedules",
    "Search schedules",
    "Find Milo schedules.",
    "read",
  ],
  [
    "milo",
    "read_schedule",
    "Read schedule",
    "Inspect a Milo schedule.",
    "read",
  ],
  [
    "milo",
    "add_schedule",
    "Add schedule",
    "Schedule a task for Milo to run later, once or on a recurring cron.",
    "write",
  ],
  [
    "milo",
    "update_schedule",
    "Update schedule",
    "Change a Milo schedule.",
    "write",
  ],
  [
    "milo",
    "delete_schedule",
    "Delete schedule",
    "Delete a Milo schedule.",
    "write",
  ],
  ["slack", "channels_list", "List channels", "List Slack channels.", "read"],
  [
    "slack",
    "conversations_history",
    "Read channel history",
    "Read Slack channel messages.",
    "read",
  ],
  [
    "slack",
    "conversations_replies",
    "Read thread replies",
    "Read Slack thread messages.",
    "read",
  ],
  [
    "slack",
    "conversations_search_messages",
    "Search messages",
    "Search Slack messages.",
    "read",
  ],
  ["slack", "users_search", "Search users", "Search Slack users.", "read"],
  [
    "slack",
    "conversations_add_message",
    "Send message",
    "Post a Slack message.",
    "write",
    "required",
  ],
  [
    "linear",
    "linear_search_issues",
    "Search issues",
    "Search Linear issues.",
    "read",
  ],
  ["linear", "linear_get_issue", "Read issue", "Read a Linear issue.", "read"],
  [
    "linear",
    "linear_list_comments",
    "Read comments",
    "Read Linear issue comments.",
    "read",
  ],
  [
    "linear",
    "linear_add_comment",
    "Add comment",
    "Add a Linear issue comment.",
    "write",
    "required",
  ],
  ...githubToolPermissionRows,
  [
    "gmail",
    "google_gmail_search_threads",
    "Search threads",
    "Search Gmail threads.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_thread",
    "Read thread",
    "Read a Gmail thread.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_message",
    "Read message",
    "Read a Gmail message.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_reply_to_thread",
    "Reply to thread",
    "Reply to the latest message in a Gmail thread.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_send_message",
    "Send email",
    "Send a new Gmail email.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_create_draft",
    "Create draft",
    "Create a Gmail draft.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_list_events",
    "List events",
    "List Google Calendar events.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_get_event",
    "Read event",
    "Read a Google Calendar event.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_create_event",
    "Create event",
    "Create a Google Calendar event.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_update_event",
    "Update event",
    "Update a Google Calendar event.",
    "write",
  ],
  ...notionToolPermissionRows,
  [
    "microsoftEmail",
    "microsoft_email_search_messages",
    "Search messages",
    "Search Outlook messages.",
    "read",
  ],
  [
    "microsoftEmail",
    "microsoft_email_get_message",
    "Read message",
    "Read an Outlook message.",
    "read",
  ],
  [
    "microsoftEmail",
    "microsoft_email_send_message",
    "Send email",
    "Send an Outlook email.",
    "write",
  ],
  [
    "microsoftEmail",
    "microsoft_email_create_draft",
    "Create draft",
    "Create an Outlook draft.",
    "write",
  ],
  [
    "microsoftEmail",
    "microsoft_email_update_message",
    "Update message",
    "Update an Outlook message or draft.",
    "write",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_list_events",
    "List events",
    "List Microsoft Calendar events.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_get_event",
    "Read event",
    "Read a Microsoft Calendar event.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_create_event",
    "Create event",
    "Create a Microsoft Calendar event.",
    "write",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_update_event",
    "Update event",
    "Update a Microsoft Calendar event.",
    "write",
  ],
] satisfies ToolPermissionRow[]
