export const skills = {
  console: {
    name: "console",
    description:
      "Format console replies as Markdown with reference cards for the resources involved and choices the requester answers in one click.",
    category: "communication",
    surfaces: ["console"],
    communication: {
      parts: {
        text: "Write the text first. It is the reply; parts hang off it, and a reader who sees nothing else should still have the answer.\n\nThe console renders Markdown:\n\n- Headings sparingly; most replies need none.\n- Tables are welcome when rows and columns make something easier to compare.\n- Fence code with a language.\n- Links as `[label](url)`.\n- No Slack `mrkdwn`: no `<url|label>` links, `*single-asterisk bold*`, or `<@id>` mentions.",
        rich: "Add a `reference` part for every resource you created or changed, and for any the requester should open next. Use the id a tool returned, with its kind (`file`, `table`, `store`, `job`, `folder`, `run`). At most six per reply.\n\nNever describe a resource in prose that a reference could show: name it in the text, and let the card carry where it is and what it is.",
        interactive:
          "A `choices` part without a `prompt` is a row of chips after the message; each sends its label as the requester's next message. When you would end a reply by listing what the requester could ask for next, put those steps in the chips instead of the text: one chip per step, phrased as the message it sends. Offer chips only when there is an obvious next step, never as filler, and at most one `choices` part per reply.\n\nWith a `prompt`, the part is a question card. Use it when you need one decision before you can continue: ask one thing, offer at most six options, set `select: \"many\"` when several can apply, and `freeform: true` when the answer is open. The requester's answer arrives as an ordinary message.",
      },
    },
    body: "## Text\n\nWrite the text first. It is the reply; parts hang off it, and a reader who sees nothing else should still have the answer.\n\nThe console renders Markdown:\n\n- Headings sparingly; most replies need none.\n- Tables are welcome when rows and columns make something easier to compare.\n- Fence code with a language.\n- Links as `[label](url)`.\n- No Slack `mrkdwn`: no `<url|label>` links, `*single-asterisk bold*`, or `<@id>` mentions.\n\n## Rich\n\nAdd a `reference` part for every resource you created or changed, and for any the requester should open next. Use the id a tool returned, with its kind (`file`, `table`, `store`, `job`, `folder`, `run`). At most six per reply.\n\nNever describe a resource in prose that a reference could show: name it in the text, and let the card carry where it is and what it is.\n\n## Interactive\n\nA `choices` part without a `prompt` is a row of chips after the message; each sends its label as the requester's next message. When you would end a reply by listing what the requester could ask for next, put those steps in the chips instead of the text: one chip per step, phrased as the message it sends. Offer chips only when there is an obvious next step, never as filler, and at most one `choices` part per reply.\n\nWith a `prompt`, the part is a question card. Use it when you need one decision before you can continue: ask one thing, offer at most six options, set `select: \"many\"` when several can apply, and `freeform: true` when the answer is open. The requester's answer arrives as an ordinary message.",
  },
  "image-generation": {
    name: "image-generation",
    description:
      "Generate a bitmap image with the `generate_image` tool and save it as a file. Use when the user asks Jori to produce an illustration, mockup, icon, texture, background, social image, or other generated picture.",
    category: "creation",
    body: '# Image Generation\n\nCall `generate_image` to create the image. Don\'t claim an image exists unless\nthe tool returned a successful file.\n\n## Writing the Prompt\n\nTurn the request into a complete, standalone prompt before calling the tool.\nCover subject, setting, composition, style, mood, materials, color constraints,\naspect expectation when implied, and any exact text that must appear. Prefer\nconcrete visual language over meta-instructions like "make it nice" or "high\nquality". State negatives only when they prevent a likely mistake.\n\n- Product or UI imagery: name the real object or interface, viewpoint, lighting,\n  and legibility requirements.\n- Icons and simple images: one central subject, plus background treatment, edge\n  style, and whether text should be absent.\n- Images with text: quote the exact text, keep it short, and require it to be\n  crisp and readable when legibility matters.\n\nThe tool only generates a new image from text — it has no transparent-output,\nreference-image, or mask-edit support. Don\'t imply otherwise; if the request\nneeds one of those, say so.\n\n## Files\n\nGenerate one image per distinct file; for several unrelated files, call the\ntool separately for each. Set `save.name` when the image has an obvious durable\nname, and `save.description` when it helps the user tell files apart later.\n\nAfter the tool succeeds, reference the returned file and workspace path. If the\nimage feeds another tool or an app, pass the returned `path` or `fileId`\ninstead of regenerating it.',
  },
  slack: {
    name: "slack",
    description:
      "Format Slack replies with native `text`, Slack `mrkdwn`, documented Block Kit blocks, links, mentions, and escaping.",
    category: "communication",
    surfaces: ["slack"],
    communication: {
      parts: {
        text: "Most replies are a line or two of plain `mrkdwn`. Reach for structure only when it earns its place.\n\nFormat Slack messages with Slack `mrkdwn`, never GitHub Markdown: no `[label](url)` links, `**double-asterisk bold**`, `# headings`, HTML, or pipe tables.\n\nUse Slack-native formatting:\n\n- `*bold*`, `_italic_`, `` `code` ``, and `>` quotes\n- Links as `<https://example.com|label>`\n- Direct mentions as `<@U123>` only with a real Slack user ID\n- Escape literal `&`, `<`, and `>` unless they are part of valid Slack syntax; emoji shortcodes don't render inside code",
        rich: "Use Slack `blocks` when structure makes the message easier to scan: results, research summaries, grouped findings, previews, anything with multiple sections. Prefer `section`, `section.fields`, `context`, `divider`, and `header`; use `table` for small tables, `data_table` when sorting or filtering helps, `data_visualization` for charts, `image` for previews, and `carousel` for several visual items. Never use interactive elements (`actions`, `context_actions`, `input`, buttons, selects, menus, modals): callbacks are not handled.",
      },
    },
    body: "## Text\n\nMost replies are a line or two of plain `mrkdwn`. Reach for structure only when it earns its place.\n\nFormat Slack messages with Slack `mrkdwn`, never GitHub Markdown: no `[label](url)` links, `**double-asterisk bold**`, `# headings`, HTML, or pipe tables.\n\nUse Slack-native formatting:\n\n- `*bold*`, `_italic_`, `` `code` ``, and `>` quotes\n- Links as `<https://example.com|label>`\n- Direct mentions as `<@U123>` only with a real Slack user ID\n- Escape literal `&`, `<`, and `>` unless they are part of valid Slack syntax; emoji shortcodes don't render inside code\n\n## Rich\n\nUse Slack `blocks` when structure makes the message easier to scan: results, research summaries, grouped findings, previews, anything with multiple sections. Prefer `section`, `section.fields`, `context`, `divider`, and `header`; use `table` for small tables, `data_table` when sorting or filtering helps, `data_visualization` for charts, `image` for previews, and `carousel` for several visual items. Never use interactive elements (`actions`, `context_actions`, `input`, buttons, selects, menus, modals): callbacks are not handled.",
  },
} as const
