/* biome-ignore-all lint/style/noExcessiveLinesPerFile: generated contract data */
// Generated by scripts/templates.ts. Do not edit by hand.
export const playbookTemplateContracts = {
  "meeting-briefing": [
    {
      name: "briefings",
      scope: "shared",
      description:
        "Canonical briefing state. Patch one meeting branch at a time and preserve unrelated meetings.",
      schemaName: "MeetingBriefings",
      schemaVersion: 3,
      schema: {
        type: "object",
        properties: {
          schemaVersion: {
            type: "number",
            const: 3,
          },
          timezone: {
            type: "string",
            maxLength: 100,
          },
          scan: {
            type: "object",
            properties: {
              scannedAt: {
                type: "string",
                format: "date-time",
                pattern:
                  "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
              },
              horizonStart: {
                type: "string",
                format: "date-time",
                pattern:
                  "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
              },
              horizonEnd: {
                type: "string",
                format: "date-time",
                pattern:
                  "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
              },
              status: {
                type: "string",
                enum: ["ready", "partial", "failed"],
              },
              gaps: {
                maxItems: 6,
                type: "array",
                items: {
                  type: "string",
                  maxLength: 160,
                },
              },
            },
            required: [
              "scannedAt",
              "horizonStart",
              "horizonEnd",
              "status",
              "gaps",
            ],
            additionalProperties: false,
          },
          meetings: {
            type: "object",
            propertyNames: {
              type: "string",
              pattern: "^mb:[0-9a-f]{32}$",
            },
            additionalProperties: {
              type: "object",
              properties: {
                event: {
                  type: "object",
                  properties: {
                    provider: {
                      type: "string",
                      maxLength: 60,
                    },
                    calendarId: {
                      type: "string",
                      maxLength: 512,
                    },
                    eventId: {
                      type: "string",
                      maxLength: 512,
                    },
                    seriesId: {
                      type: "string",
                      maxLength: 512,
                    },
                    title: {
                      type: "string",
                      maxLength: 200,
                    },
                    startsAt: {
                      type: "string",
                      format: "date-time",
                      pattern:
                        "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                    },
                    endsAt: {
                      type: "string",
                      format: "date-time",
                      pattern:
                        "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                    },
                    status: {
                      type: "string",
                      maxLength: 40,
                    },
                    fingerprint: {
                      type: "string",
                      pattern: "^[0-9a-f]{64}$",
                    },
                    organizer: {
                      type: "object",
                      properties: {
                        name: {
                          type: "string",
                          maxLength: 80,
                        },
                        organization: {
                          type: "string",
                          maxLength: 80,
                        },
                        role: {
                          type: "string",
                          maxLength: 80,
                        },
                        response: {
                          type: "string",
                          enum: [
                            "accepted",
                            "tentative",
                            "declined",
                            "unknown",
                          ],
                        },
                      },
                      additionalProperties: false,
                    },
                    attendees: {
                      maxItems: 6,
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          name: {
                            type: "string",
                            maxLength: 80,
                          },
                          organization: {
                            type: "string",
                            maxLength: 80,
                          },
                          role: {
                            type: "string",
                            maxLength: 80,
                          },
                          response: {
                            type: "string",
                            enum: [
                              "accepted",
                              "tentative",
                              "declined",
                              "unknown",
                            ],
                          },
                        },
                        additionalProperties: false,
                      },
                    },
                    location: {
                      type: "string",
                      maxLength: 200,
                    },
                  },
                  required: [
                    "provider",
                    "eventId",
                    "title",
                    "startsAt",
                    "endsAt",
                    "status",
                    "fingerprint",
                    "attendees",
                  ],
                  additionalProperties: false,
                },
                whyItMatters: {
                  type: "string",
                  maxLength: 160,
                },
                status: {
                  type: "string",
                  enum: [
                    "queued",
                    "researching",
                    "ready",
                    "partial",
                    "sparse",
                    "failed",
                    "stale",
                    "cancelled",
                  ],
                },
                revision: {
                  type: "integer",
                  minimum: 0,
                  maximum: 9007199254740991,
                },
                preparedAt: {
                  type: "string",
                  format: "date-time",
                  pattern:
                    "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                },
                preparedForFingerprint: {
                  type: "string",
                  pattern: "^[0-9a-f]{64}$",
                },
                briefing: {
                  type: "object",
                  properties: {
                    purpose: {
                      type: "object",
                      properties: {
                        text: {
                          type: "string",
                          maxLength: 240,
                        },
                        kind: {
                          type: "string",
                          enum: ["fact", "inference", "recommendation"],
                        },
                        area: {
                          type: "string",
                          enum: [
                            "purpose",
                            "agenda",
                            "person",
                            "history",
                            "commitment",
                            "development",
                            "decision",
                            "talking-point",
                            "question",
                            "risk",
                          ],
                        },
                        sourceIds: {
                          minItems: 1,
                          maxItems: 3,
                          type: "array",
                          items: {
                            type: "string",
                            maxLength: 60,
                          },
                        },
                      },
                      required: ["text", "kind", "area", "sourceIds"],
                      additionalProperties: false,
                    },
                    outcome: {
                      type: "string",
                      maxLength: 240,
                    },
                    essentials: {
                      maxItems: 3,
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          text: {
                            type: "string",
                            maxLength: 240,
                          },
                          kind: {
                            type: "string",
                            enum: ["fact", "inference", "recommendation"],
                          },
                          area: {
                            type: "string",
                            enum: [
                              "purpose",
                              "agenda",
                              "person",
                              "history",
                              "commitment",
                              "development",
                              "decision",
                              "talking-point",
                              "question",
                              "risk",
                            ],
                          },
                          sourceIds: {
                            minItems: 1,
                            maxItems: 3,
                            type: "array",
                            items: {
                              type: "string",
                              maxLength: 60,
                            },
                          },
                        },
                        required: ["text", "kind", "area", "sourceIds"],
                        additionalProperties: false,
                      },
                    },
                    details: {
                      maxItems: 5,
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          text: {
                            type: "string",
                            maxLength: 240,
                          },
                          kind: {
                            type: "string",
                            enum: ["fact", "inference", "recommendation"],
                          },
                          area: {
                            type: "string",
                            enum: [
                              "purpose",
                              "agenda",
                              "person",
                              "history",
                              "commitment",
                              "development",
                              "decision",
                              "talking-point",
                              "question",
                              "risk",
                            ],
                          },
                          sourceIds: {
                            minItems: 1,
                            maxItems: 3,
                            type: "array",
                            items: {
                              type: "string",
                              maxLength: 60,
                            },
                          },
                        },
                        required: ["text", "kind", "area", "sourceIds"],
                        additionalProperties: false,
                      },
                    },
                    unknowns: {
                      maxItems: 4,
                      type: "array",
                      items: {
                        type: "string",
                        maxLength: 160,
                      },
                    },
                  },
                  required: ["essentials", "details", "unknowns"],
                  additionalProperties: false,
                },
                sources: {
                  maxItems: 4,
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      id: {
                        type: "string",
                        maxLength: 60,
                      },
                      kind: {
                        type: "string",
                        maxLength: 40,
                      },
                      label: {
                        type: "string",
                        maxLength: 120,
                      },
                      occurredAt: {
                        type: "string",
                        format: "date-time",
                        pattern:
                          "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                      },
                      retrievedAt: {
                        type: "string",
                        format: "date-time",
                        pattern:
                          "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                      },
                      url: {
                        type: "string",
                        maxLength: 400,
                      },
                    },
                    required: ["id", "kind", "label", "retrievedAt"],
                    additionalProperties: false,
                  },
                },
                delivery: {
                  type: "object",
                  properties: {
                    morning: {
                      type: "object",
                      properties: {
                        revision: {
                          type: "integer",
                          minimum: 0,
                          maximum: 9007199254740991,
                        },
                        eventStartsAt: {
                          type: "string",
                          format: "date-time",
                          pattern:
                            "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                        },
                        deliveredAt: {
                          type: "string",
                          format: "date-time",
                          pattern:
                            "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                        },
                        destination: {
                          type: "string",
                          enum: ["email", "slack-dm"],
                        },
                      },
                      required: [
                        "revision",
                        "eventStartsAt",
                        "deliveredAt",
                        "destination",
                      ],
                      additionalProperties: false,
                    },
                    reminder: {
                      type: "object",
                      properties: {
                        revision: {
                          type: "integer",
                          minimum: 0,
                          maximum: 9007199254740991,
                        },
                        eventStartsAt: {
                          type: "string",
                          format: "date-time",
                          pattern:
                            "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                        },
                        deliveredAt: {
                          type: "string",
                          format: "date-time",
                          pattern:
                            "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                        },
                        destination: {
                          type: "string",
                          enum: ["email", "slack-dm"],
                        },
                      },
                      required: [
                        "revision",
                        "eventStartsAt",
                        "deliveredAt",
                        "destination",
                      ],
                      additionalProperties: false,
                    },
                  },
                  additionalProperties: false,
                },
              },
              required: [
                "event",
                "whyItMatters",
                "status",
                "revision",
                "sources",
              ],
              additionalProperties: false,
            },
          },
          dispatches: {
            type: "object",
            propertyNames: {
              type: "string",
              pattern: "^md:[0-9a-f]{32}$",
            },
            additionalProperties: {
              type: "object",
              properties: {
                kind: {
                  type: "string",
                  enum: ["morning", "reminder", "manual", "failure"],
                },
                payloadHash: {
                  type: "string",
                  pattern: "^[0-9a-f]{64}$",
                },
                status: {
                  type: "string",
                  enum: ["sending", "delivered", "failed", "unknown"],
                },
                attemptedAt: {
                  type: "string",
                  format: "date-time",
                  pattern:
                    "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                },
                updatedAt: {
                  type: "string",
                  format: "date-time",
                  pattern:
                    "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                },
                deliveredAt: {
                  type: "string",
                  format: "date-time",
                  pattern:
                    "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                },
                destination: {
                  type: "string",
                  enum: ["email", "slack-dm"],
                },
                error: {
                  type: "string",
                  maxLength: 160,
                },
              },
              required: [
                "kind",
                "payloadHash",
                "status",
                "attemptedAt",
                "updatedAt",
                "destination",
              ],
              additionalProperties: false,
            },
          },
        },
        required: [
          "schemaVersion",
          "timezone",
          "scan",
          "meetings",
          "dispatches",
        ],
        additionalProperties: false,
      },
    },
    {
      name: "research",
      scope: "personal",
      description:
        "Temporary research working state. Clear each attempt after synthesis.",
      schemaName: "MeetingBriefingResearch",
      schemaVersion: 3,
      schema: {
        type: "object",
        properties: {
          schemaVersion: {
            type: "number",
            const: 3,
          },
          attempts: {
            type: "object",
            propertyNames: {
              type: "string",
              pattern: "^mb:[0-9a-f]{32}$",
            },
            additionalProperties: {
              type: "object",
              properties: {
                attemptId: {
                  type: "string",
                  maxLength: 60,
                },
                eventFingerprint: {
                  type: "string",
                  pattern: "^[0-9a-f]{64}$",
                },
                status: {
                  type: "string",
                  enum: ["pending", "ready", "partial", "sparse", "failed"],
                },
                startedAt: {
                  type: "string",
                  format: "date-time",
                  pattern:
                    "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                },
                completedAt: {
                  type: "string",
                  format: "date-time",
                  pattern:
                    "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                },
                findings: {
                  maxItems: 8,
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: {
                        type: "string",
                        maxLength: 240,
                      },
                      kind: {
                        type: "string",
                        enum: ["fact", "inference", "recommendation"],
                      },
                      area: {
                        type: "string",
                        enum: [
                          "purpose",
                          "agenda",
                          "person",
                          "history",
                          "commitment",
                          "development",
                          "decision",
                          "talking-point",
                          "question",
                          "risk",
                        ],
                      },
                      sourceIds: {
                        minItems: 1,
                        maxItems: 3,
                        type: "array",
                        items: {
                          type: "string",
                          maxLength: 60,
                        },
                      },
                    },
                    required: ["text", "kind", "area", "sourceIds"],
                    additionalProperties: false,
                  },
                },
                sources: {
                  maxItems: 4,
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      id: {
                        type: "string",
                        maxLength: 60,
                      },
                      kind: {
                        type: "string",
                        maxLength: 40,
                      },
                      label: {
                        type: "string",
                        maxLength: 120,
                      },
                      occurredAt: {
                        type: "string",
                        format: "date-time",
                        pattern:
                          "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                      },
                      retrievedAt: {
                        type: "string",
                        format: "date-time",
                        pattern:
                          "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
                      },
                      url: {
                        type: "string",
                        maxLength: 400,
                      },
                    },
                    required: ["id", "kind", "label", "retrievedAt"],
                    additionalProperties: false,
                  },
                },
                gaps: {
                  maxItems: 4,
                  type: "array",
                  items: {
                    type: "string",
                    maxLength: 160,
                  },
                },
              },
              required: [
                "attemptId",
                "eventFingerprint",
                "status",
                "startedAt",
                "findings",
                "sources",
                "gaps",
              ],
              additionalProperties: false,
            },
          },
        },
        required: ["schemaVersion", "attempts"],
        additionalProperties: false,
      },
    },
  ],
} as const
