// Generated by scripts/templates.ts. Do not edit by hand.
export const playbookTemplateContracts = {
  "meeting-briefing": [
    {
      name: "briefings",
      scope: "shared",
      description:
        "Canonical Meeting Briefing state. Patch one meeting branch at a time and preserve unrelated meetings.",
      schemaName: "MeetingBriefings",
      schemaVersion: 3,
    },
    {
      name: "research",
      scope: "personal",
      description:
        "Private, temporary Meeting Briefing research. Clear each attempt after synthesis.",
      schemaName: "MeetingBriefingResearch",
      schemaVersion: 3,
    },
  ],
} as const
