import { expect, test } from "vitest"
import { databaseContext } from "../../test/convex/database"
import { type Id } from "../_generated/dataModel"
import { type QueryCtx } from "../_generated/server"
import { forRun } from "./data"

const handler = (
  forRun as unknown as {
    _handler: (
      ctx: QueryCtx,
      args: { fileId: Id<"files">; runId: Id<"runs"> }
    ) => Promise<{ storageId: Id<"_storage">; size: number }>
  }
)._handler

test("returns only the storage reference for a file generated by the owning run", async () => {
  const { ctx, args } = await fixture()
  await expect(handler(ctx, args)).resolves.toEqual({
    storageId: "storage-1",
    size: 12,
  })
})

test("rejects a different run even within the same organization", async () => {
  const { ctx, database, args } = await fixture()
  const runId = await database.insert("runs", {
    organizationId: "organization-1",
  })
  await expect(handler(ctx, { ...args, runId })).rejects.toThrow(
    "File does not belong to this run."
  )
})

test("rejects mismatched organizations even with a matching run reference", async () => {
  const { ctx, database, args } = await fixture()
  await database.patch(args.fileId, { organizationId: "organization-2" })
  await expect(handler(ctx, args)).rejects.toThrow(
    "File does not belong to this run."
  )
})

test.each(["fileId", "runId"] as const)(
  "rejects a missing %s",
  async (field) => {
    const { ctx, database, args } = await fixture()
    await database.delete(args[field])
    await expect(handler(ctx, args)).rejects.toThrow(
      "File does not belong to this run."
    )
  }
)

async function fixture() {
  const { ctx, database } = databaseContext()
  const runId = await database.insert("runs", {
    organizationId: "organization-1",
  })
  const fileId = await database.insert("files", {
    organizationId: "organization-1",
    runId,
    storageId: "storage-1",
    size: 12,
  })
  return { ctx, database, args: { fileId, runId } }
}
