import { type ToolPermissionRow } from "../types"

export const googleToolPermissionRows = [
  [
    "gmail",
    "google_gmail_search_threads",
    "Search threads",
    "Search your Gmail threads.",
    "Search Gmail threads with a Gmail query, including operators like from: and newer_than:. Use to narrow to relevant threads before reading; prefer the batch read for several hits.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_thread",
    "Read thread",
    "Read a Gmail thread.",
    "Read one Gmail thread in full. Use after search to get the messages before replying or summarizing.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_threads",
    "Read threads",
    "Read several Gmail threads at once.",
    "Read multiple Gmail threads in one call. Prefer this over repeated single-thread reads after a search.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_message",
    "Read message",
    "Read a single Gmail message.",
    "Read one Gmail message by id. Use when you need a specific message rather than the whole thread.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_messages",
    "Read messages",
    "Read several Gmail messages at once.",
    "Read multiple Gmail messages in one call. Prefer this over repeated single-message reads.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_reply_to_thread",
    "Reply to thread",
    "Reply to a Gmail thread.",
    "Reply to the latest message in a Gmail thread; it sends immediately as plain text without attachments. Use to continue an existing conversation; create a draft with threadId when the requester should review the reply first.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_send_message",
    "Send email",
    "Send a new email from your Gmail account.",
    "Send a new Gmail email, optionally attaching saved run assets. Use for a fresh message; reply to the thread when continuing a conversation, or create a draft when the requester should review it first.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_create_draft",
    "Create draft",
    "Save a Gmail draft without sending.",
    "Create a Gmail draft for the requester to review and send. Prefer this over sending when the email should be approved first; set threadId to draft a reply in an existing thread.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_list_calendars",
    "List calendars",
    "List calendars in your Google Calendar account.",
    "List Google calendars before searching events when work may live outside the primary calendar.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_list_events",
    "List calendar events",
    "List events across your Google calendars.",
    "List Google Calendar events in a time range across every readable calendar, or pass a calendar ID to target one. Use to check availability or find an event before reading or changing it. Each event carries entityKey (stable identity) and contentHash (changes when its content changes); use them instead of computing your own keys or fingerprints.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_get_event",
    "Read calendar event",
    "Read a Google Calendar event.",
    "Read one Google Calendar event's details. Use to confirm specifics before updating or referencing it. Pass the calendar ID the event was listed under so its entityKey stays stable; the result carries entityKey and contentHash.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_create_event",
    "Create calendar event",
    "Add an event to your Google Calendar.",
    "Create a Google Calendar event. Confirm time, attendees, and title before creating.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_update_event",
    "Update calendar event",
    "Change an event on your Google Calendar.",
    "Update an existing Google Calendar event. Read it first to preserve fields you are not changing.",
    "write",
  ],
] satisfies ToolPermissionRow[]
