import { type ToolPermissionRow } from "../types"

export const joriToolPermissionRows = [
  // Run control
  [
    "jori",
    "list_capabilities",
    "List capabilities",
    "See the tools and integrations available in this run.",
    "List current run tools, connected integration capabilities, and integrations available to connect. Use to discover what you can do before acting or offering a connection.",
    "read",
    "required",
  ],
  [
    "jori",
    "load_skill",
    "Load skill",
    "Load detailed instructions for one of Jori's skills.",
    "Load full instructions for an available skill before doing specialized work it covers, such as generating an image.",
    "read",
    "required",
  ],
  [
    "jori",
    "search_runs",
    "Search runs",
    "Find Jori's past and ongoing runs.",
    "Use mode search to browse visible runs; query is a case-insensitive substring over title, task, trigger, and context labels. Use ids for known run IDs, including the current Run ID from context. Use children or tree only when navigating known run IDs. Visibility is enforced, so missing results do not prove nothing happened.",
    "read",
  ],
  [
    "jori",
    "search_run_activity",
    "Search run activity",
    "See what happened during a Jori run.",
    "Inspect one visible run after search_runs, or inspect the active run with the current Run ID from context. Use filters and pagination instead of enumerating everything. Summarized model reasoning may be available on model activity items as incomplete intent context, not a verbatim transcript. Raw tool payloads are not available; cite the inspected runId.",
    "read",
  ],
  [
    "jori",
    "read_workstreams",
    "Read workstreams",
    "Read the organization's workstream roster and its recent activity.",
    "Read the deduced workstream roster with each workstream's recent journal entries and their citation links inside a day window; defaults to the last week. Workstreams with no entries in the window went quiet, which is signal, not absence. Use before summarizing what moved, stalled, or shipped, and cite the returned links.",
    "read",
  ],
  [
    "jori",
    "offer_integration",
    "Offer integration",
    "Offer to connect an integration so Jori can use it.",
    "Offer an integration the run needs and surface it in the active conversation. Include a concise summary for the offer card.",
    "write",
    "required",
  ],
  [
    "jori",
    "cancel_approval_request",
    "Cancel approval request",
    "Withdraw an approval request Jori is waiting on.",
    "Withdraw a pending approval request when the requester asks to cancel it. Requires a short reason and the Jori internal message id of the message that requested cancellation.",
    "write",
    "required",
  ],
  [
    "jori",
    "cancel_integration_offer",
    "Cancel integration offer",
    "Withdraw an integration offer Jori previously made.",
    "Withdraw an integration offer you made earlier in this run when it is no longer needed. Requires a short reason.",
    "write",
    "required",
  ],
  // Files
  [
    "jori",
    "save_file",
    "Save file",
    "Save a file Jori created so it can be sent or reused.",
    "Save a sandbox file to the organization's files and get the file id that sending tools require. Use after producing a file the requester needs delivered or kept; messages, emails, and uploads can only attach saved files.",
    "write",
    "required",
  ],
  [
    "jori",
    "generate_image",
    "Generate image",
    "Generate an image and save it to this run.",
    "Generate a new bitmap image from a text prompt and save it as a file. Use for illustrations, mockups, icons, diagrams, or backgrounds. Text input only — no reference-image or mask editing.",
    "write",
  ],
  [
    "jori",
    "search_files",
    "Search files",
    "Find the organization's saved files.",
    "Find saved files by name, description, or content type. Use to reuse or send an existing file instead of recreating it.",
    "read",
  ],
  [
    "jori",
    "read_file",
    "Read file",
    "Open one of the organization's saved files.",
    "Inspect a saved file by id. Use to read its contents or metadata before reusing, sending, or referencing it.",
    "read",
  ],
  // Jobs
  [
    "jori",
    "search_jobs",
    "Search jobs",
    "Find existing user-managed Jori jobs.",
    "Find top-level jobs by name or instruction text. Internal scheduled work is omitted. Use to locate a job before reading or changing it, and to check for an existing job before adding a duplicate. When you already have a job ID, use read_job directly.",
    "read",
  ],
  [
    "jori",
    "read_job",
    "Read job",
    "Read a job's setup.",
    "Inspect a job's trigger and instructions. Use before updating, or to confirm what it does.",
    "read",
  ],
  [
    "jori",
    "add_job",
    "Add job",
    "Set up a task that runs on a schedule or event.",
    "Create a task that runs once at a set time, on a cron schedule, or on an integration event. Write canonical Markdown instructions with @Integration access references, /skill references, #tool references, and txt fences for reference-capable plain text. Keep explicit access aligned with the integration tools the instructions reference.",
    "write",
  ],
  [
    "jori",
    "update_job",
    "Update job",
    "Change a Jori job.",
    "Change a job's trigger or instructions. Read it first to preserve settings you are not changing. Write canonical Markdown instructions with @Integration access references, /skill references, #tool references, and txt fences for reference-capable plain text. Keep explicit access aligned with the integration tools the instructions reference.",
    "write",
  ],
  [
    "jori",
    "delete_job",
    "Delete job",
    "Delete a Jori job.",
    "Delete a job when it is no longer needed. Confirm intent before deleting.",
    "write",
  ],
] satisfies ToolPermissionRow[]
