import { type ToolPermissionRow } from "../types"

export const joriToolPermissionRows = [
  // Run control
  [
    "jori",
    "list_capabilities",
    "List capabilities",
    "See the tools and integrations available in this run.",
    "List current run tools, connected integration capabilities, and integrations available to connect. Use to discover what you can do before acting or offering a connection.",
    "read",
    "required",
  ],
  [
    "jori",
    "load_skill",
    "Load skill",
    "Load detailed instructions for one of Jori's skills.",
    "Load full instructions for an available skill before doing specialized work it covers, such as building an app or generating an image.",
    "read",
    "required",
  ],
  [
    "jori",
    "search_runs",
    "Search runs",
    "Find Jori's past and ongoing runs.",
    "Use mode search to browse visible runs; query is a case-insensitive substring over title, task, trigger, and context labels. Use ids for known run IDs, including the current Run ID from context. Use children or tree only when navigating known run IDs. Visibility is enforced, so missing results do not prove nothing happened.",
    "read",
  ],
  [
    "jori",
    "search_run_activity",
    "Search run activity",
    "See what happened during a Jori run.",
    "Inspect one visible run after search_runs, or inspect the active run with the current Run ID from context. Use filters and pagination instead of enumerating everything. Summarized model reasoning may be available on model activity items as incomplete intent context, not a verbatim transcript. Raw tool payloads are not available; cite the inspected runId.",
    "read",
  ],
  [
    "jori",
    "read_workstreams",
    "Read workstreams",
    "Read the organization's workstream roster and its recent activity.",
    "Read the deduced workstream roster with each workstream's recent journal entries and their citation links inside a day window; defaults to the last week. Workstreams with no entries in the window went quiet, which is signal, not absence. Use before summarizing what moved, stalled, or shipped, and cite the returned links.",
    "read",
  ],
  [
    "jori",
    "offer_integration",
    "Offer integration",
    "Offer to connect an integration so Jori can use it.",
    "Offer an integration the run needs and surface it in the active conversation. Include a concise summary for the offer card.",
    "write",
    "required",
  ],
  [
    "jori",
    "cancel_approval_request",
    "Cancel approval request",
    "Withdraw an approval request Jori is waiting on.",
    "Withdraw a pending approval request when the requester asks to cancel it. Requires a short reason and the Jori internal message id of the message that requested cancellation.",
    "write",
    "required",
  ],
  [
    "jori",
    "cancel_integration_offer",
    "Cancel integration offer",
    "Withdraw an integration offer Jori previously made.",
    "Withdraw an integration offer you made earlier in this run when it is no longer needed. Requires a short reason.",
    "write",
    "required",
  ],
  // Assets
  [
    "jori",
    "save_asset",
    "Save asset",
    "Save a file Jori created so it can be sent or reused.",
    "Save a sandbox file as a run asset and get the asset id that sending tools require. Use after producing a file the requester needs delivered or kept; messages, emails, and uploads can only attach saved assets.",
    "write",
    "required",
  ],
  [
    "jori",
    "generate_image",
    "Generate image",
    "Generate an image and save it to this run.",
    "Generate a new bitmap image from a text prompt and save it as a run asset. Use for illustrations, mockups, icons, diagrams, or backgrounds. Text input only — no reference-image or mask editing.",
    "write",
  ],
  [
    "jori",
    "search_assets",
    "Search assets",
    "Find files saved to this run.",
    "Find saved run assets by name, description, or content type. Use to reuse or send an existing asset instead of recreating it.",
    "read",
  ],
  [
    "jori",
    "read_asset",
    "Read asset",
    "Open a file saved to this run.",
    "Inspect a saved run asset by id. Use to read its contents or metadata before reusing, sending, or referencing it.",
    "read",
  ],
  // Apps
  [
    "jori",
    "search_apps",
    "Search apps",
    "Find existing Jori apps.",
    "Find Jori apps by title. Use to locate an app before reading or updating it.",
    "read",
  ],
  [
    "jori",
    "read_app",
    "Read app",
    "Read an app's source.",
    "Inspect an app's source snapshot. Use before updating to see the current files, or to reuse a pattern.",
    "read",
  ],
  [
    "jori",
    "read_app_state",
    "Read app state",
    "Read an app's saved data.",
    "Read a scoped JSON state document for an app. Use to inspect contract-backed state the UI or an automation wrote.",
    "read",
  ],
  [
    "jori",
    "create_app",
    "Create app",
    "Build and publish a new interactive app.",
    "Validate, publish, and return the open path for a new app from a workspace folder. Use after local checks pass; pass workspacePath, never inline source. Load the app-creator skill first.",
    "write",
  ],
  [
    "jori",
    "update_app",
    "Update app",
    "Publish a new version of an app.",
    "Validate and publish a new version of an existing app. Read the current source first; pass workspacePath, never inline source.",
    "write",
  ],
  [
    "jori",
    "delete_app",
    "Delete app",
    "Archive or permanently delete an app.",
    "Archive an active app, or permanently delete an already-archived one. Confirm intent before deleting.",
    "write",
  ],
  [
    "jori",
    "update_app_state",
    "Update app state",
    "Write data into an app's saved state.",
    "Replace, merge-patch, or claim into a contract-bound state document, keyed by contractName; writes must match the contract schema and stay within the 256 KiB document cap. A claim atomically sets a path only when it is still unset — claim before at-most-once actions like sending. appId defaults to the automation run's primary app — pass it explicitly for any other app.",
    "write",
  ],
  [
    "jori",
    "share_app",
    "Share app",
    "Create a time-limited link that lets anyone view an app.",
    "Mint a view-only link for an app that works without signing in to Jori. Use when delivering an app to people who may lack Jori access, and include the returned url in your message. Viewers see published assets and shared-scope state only. Each call creates an independent link with its own expiry; earlier links keep working until they expire.",
    "write",
  ],
  // Automations
  [
    "jori",
    "search_automations",
    "Search automations",
    "Find existing user-managed Jori automations.",
    "Find top-level automations by name or instruction text. Internal scheduled work is omitted. Use to locate an automation before reading or changing it, and to check for an existing automation before adding a duplicate. When you already have an automation ID, use read_automation directly.",
    "read",
  ],
  [
    "jori",
    "read_automation",
    "Read automation",
    "Read an automation's setup.",
    "Inspect an automation's trigger and instructions. Use before updating, or to confirm what it does.",
    "read",
  ],
  [
    "jori",
    "add_automation",
    "Add automation",
    "Set up a task that runs on a schedule or event.",
    "Create a task that runs once at a set time, on a cron schedule, or on an integration event. Write canonical Markdown instructions with @Integration access references, /skill references, #tool references, and txt fences for reference-capable plain text. Keep explicit access aligned with the integration tools the instructions reference. Set appId to the automation's primary app when it drives one: state tools default to it, and instructions may still reference other apps by ID.",
    "write",
  ],
  [
    "jori",
    "update_automation",
    "Update automation",
    "Change a Jori automation.",
    "Change an automation's trigger or instructions. Read it first to preserve settings you are not changing. Write canonical Markdown instructions with @Integration access references, /skill references, #tool references, and txt fences for reference-capable plain text. Keep explicit access aligned with the integration tools the instructions reference.",
    "write",
  ],
  [
    "jori",
    "delete_automation",
    "Delete automation",
    "Delete a Jori automation.",
    "Delete an automation when it is no longer needed. Confirm intent before deleting.",
    "write",
  ],
] satisfies ToolPermissionRow[]
