import { type ToolPermissionRow } from "../types"

export const microsoftToolPermissionRows = [
  [
    "microsoftEmail",
    "microsoft_email_search_messages",
    "Search messages",
    "Search your Outlook messages.",
    "Search Outlook messages by query. Use to narrow to relevant mail before reading.",
    "read",
  ],
  [
    "microsoftEmail",
    "microsoft_email_get_message",
    "Read message",
    "Read an Outlook message.",
    "Read one Outlook message. Use after search to get the full message before replying.",
    "read",
  ],
  [
    "microsoftEmail",
    "microsoft_email_send_message",
    "Send email",
    "Send a new email from your Outlook account.",
    "Send a new Outlook email, optionally attaching saved run assets. Use for a fresh message; create a draft instead when the requester should review it first.",
    "write",
  ],
  [
    "microsoftEmail",
    "microsoft_email_create_draft",
    "Create draft",
    "Save an Outlook draft without sending.",
    "Create an Outlook draft for the requester to review and send. Prefer this over sending when the email should be approved first.",
    "write",
  ],
  [
    "microsoftEmail",
    "microsoft_email_update_message",
    "Update message",
    "Update an Outlook message or draft.",
    "Update an Outlook message or draft. Use to revise a draft before it is sent.",
    "write",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_list_calendars",
    "List calendars",
    "List calendars in your Microsoft Calendar account.",
    "List Microsoft calendars before searching events when work may live outside the default calendar.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_list_events",
    "List calendar events",
    "List events across your Microsoft calendars.",
    "List Microsoft Calendar events in a time range across every readable calendar, or pass a calendar ID to target one. Use to check availability or find an event before changing it. Each event carries entityKey (stable identity) and contentHash (changes when its content changes); use them instead of computing your own keys or fingerprints.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_get_event",
    "Read calendar event",
    "Read a Microsoft Calendar event.",
    "Read one Microsoft Calendar event's details. Use to confirm specifics before updating. Pass the calendar ID the event was listed under so its entityKey stays stable; the result carries entityKey and contentHash.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_create_event",
    "Create calendar event",
    "Add an event to your Microsoft Calendar.",
    "Create a Microsoft Calendar event. Confirm time, attendees, and title before creating.",
    "write",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_update_event",
    "Update calendar event",
    "Change an event on your Microsoft Calendar.",
    "Update an existing Microsoft Calendar event. Read it first to preserve fields you are not changing.",
    "write",
  ],
] satisfies ToolPermissionRow[]
