import { type ToolPermissionRow } from "../types"

export const miloToolPermissionRows = [
  // Run control
  [
    "milo",
    "list_capabilities",
    "List capabilities",
    "See the tools and integrations available in this run.",
    "List current run tools, connected integration capabilities, and integrations available to connect. Use to discover what you can do before acting or offering a connection.",
    "read",
    "required",
  ],
  [
    "milo",
    "load_skill",
    "Load skill",
    "Load detailed instructions for one of Milo's skills.",
    "Load full instructions for an available skill before doing specialized work it covers, such as building an artifact or generating an image.",
    "read",
    "required",
  ],
  [
    "milo",
    "search_runs",
    "Search runs",
    "Find Milo's past and ongoing runs.",
    "Use mode search to browse visible runs; query is a case-insensitive substring over title, task, trigger, and context labels. Use ids for known run IDs, including the current Run ID from context. Use children or tree only when navigating known run IDs. Visibility is enforced, so missing results do not prove nothing happened.",
    "read",
  ],
  [
    "milo",
    "search_run_activity",
    "Search run activity",
    "See what happened during a Milo run.",
    "Inspect one visible run after search_runs, or inspect the active run with the current Run ID from context. Use filters and pagination instead of enumerating everything. Summarized model reasoning may be available on model activity items as incomplete intent context, not a verbatim transcript. Raw tool payloads are not available; cite the inspected runId.",
    "read",
  ],
  [
    "milo",
    "offer_integration",
    "Offer integration",
    "Offer to connect an integration so Milo can use it.",
    "Offer an integration the run needs and surface it in the active conversation. Include a concise summary for the offer card.",
    "write",
    "required",
  ],
  [
    "milo",
    "cancel_approval_request",
    "Cancel approval request",
    "Withdraw an approval request Milo is waiting on.",
    "Withdraw a pending approval request when the requester asks to cancel it. Requires a short reason and the Milo internal message id of the message that requested cancellation.",
    "write",
    "required",
  ],
  [
    "milo",
    "cancel_integration_offer",
    "Cancel integration offer",
    "Withdraw an integration offer Milo previously made.",
    "Withdraw an integration offer you made earlier in this run when it is no longer needed. Requires a short reason.",
    "write",
    "required",
  ],
  // Assets
  [
    "milo",
    "save_asset",
    "Save asset",
    "Save a file Milo created so it can be sent or reused.",
    "Save a sandbox file as a run asset and get the asset id that sending tools require. Use after producing a file the requester needs delivered or kept; messages, emails, and uploads can only attach saved assets.",
    "write",
    "required",
  ],
  [
    "milo",
    "generate_image",
    "Generate image",
    "Generate an image and save it to this run.",
    "Generate a new bitmap image from a text prompt and save it as a run asset. Use for illustrations, mockups, icons, diagrams, or backgrounds. Text input only — no reference-image or mask editing.",
    "write",
  ],
  [
    "milo",
    "search_assets",
    "Search assets",
    "Find files saved to this run.",
    "Find saved run assets by name, description, or content type. Use to reuse or send an existing asset instead of recreating it.",
    "read",
  ],
  [
    "milo",
    "read_asset",
    "Read asset",
    "Open a file saved to this run.",
    "Inspect a saved run asset by id. Use to read its contents or metadata before reusing, sending, or referencing it.",
    "read",
  ],
  // Artifacts
  [
    "milo",
    "search_artifacts",
    "Search artifacts",
    "Find existing Milo artifacts.",
    "Find Milo artifacts by title. Use to locate an artifact before reading or updating it.",
    "read",
  ],
  [
    "milo",
    "read_artifact",
    "Read artifact",
    "Read an artifact's source.",
    "Inspect an artifact's source snapshot. Use before updating to see the current files, or to reuse a pattern.",
    "read",
  ],
  [
    "milo",
    "read_artifact_state",
    "Read artifact state",
    "Read an artifact's saved data.",
    "Read a scoped JSON state document for an artifact. Use to inspect contract-backed state the UI or an automation wrote.",
    "read",
  ],
  [
    "milo",
    "create_artifact",
    "Create artifact",
    "Build and publish a new interactive artifact.",
    "Validate, publish, and return the open path for a new artifact from a workspace folder. Use after local checks pass; pass workspacePath, never inline source. Load the artifact-creator skill first.",
    "write",
  ],
  [
    "milo",
    "update_artifact",
    "Update artifact",
    "Publish a new version of an artifact.",
    "Validate and publish a new version of an existing artifact. Read the current source first; pass workspacePath, never inline source.",
    "write",
  ],
  [
    "milo",
    "delete_artifact",
    "Delete artifact",
    "Archive or permanently delete an artifact.",
    "Archive an active artifact, or permanently delete an already-archived one. Confirm intent before deleting.",
    "write",
  ],
  [
    "milo",
    "update_artifact_state",
    "Update artifact state",
    "Write data into an artifact's saved state.",
    "Replace, merge-patch, or claim into a contract-bound state document, keyed by contractName; writes must match the contract schema and stay within the 256 KiB document cap. A claim atomically sets a path only when it is still unset — claim before at-most-once actions like sending. artifactId defaults to the automation run's primary artifact — pass it explicitly for any other artifact.",
    "write",
  ],
  [
    "milo",
    "share_artifact",
    "Share artifact",
    "Create a time-limited link that lets anyone view an artifact.",
    "Mint a view-only link for an artifact that works without signing in to Milo. Use when delivering an artifact to people who may lack Milo access, and include the returned url in your message. Viewers see published assets and shared-scope state only. Each call creates an independent link with its own expiry; earlier links keep working until they expire.",
    "write",
  ],
  // Automations
  [
    "milo",
    "search_automations",
    "Search automations",
    "Find existing user-managed Milo automations.",
    "Find top-level automations by name or instruction text. Internal scheduled work is omitted. Use to locate an automation before reading or changing it, and to check for an existing automation before adding a duplicate. When you already have an automation ID, use read_automation directly.",
    "read",
  ],
  [
    "milo",
    "read_automation",
    "Read automation",
    "Read an automation's setup.",
    "Inspect an automation's trigger and instructions. Use before updating, or to confirm what it does.",
    "read",
  ],
  [
    "milo",
    "add_automation",
    "Add automation",
    "Set up a task that runs on a schedule or event.",
    "Create a task that runs once at a set time, on a cron schedule, or on an integration event. Write canonical Markdown instructions with @Integration access references, /skill references, #tool references, and txt fences for reference-capable plain text. Keep explicit access aligned with the integration tools the instructions reference. Set artifactId to the automation's primary artifact when it drives one: state tools default to it, and instructions may still reference other artifacts by ID.",
    "write",
  ],
  [
    "milo",
    "update_automation",
    "Update automation",
    "Change a Milo automation.",
    "Change an automation's trigger or instructions. Read it first to preserve settings you are not changing. Write canonical Markdown instructions with @Integration access references, /skill references, #tool references, and txt fences for reference-capable plain text. Keep explicit access aligned with the integration tools the instructions reference.",
    "write",
  ],
  [
    "milo",
    "delete_automation",
    "Delete automation",
    "Delete a Milo automation.",
    "Delete an automation when it is no longer needed. Confirm intent before deleting.",
    "write",
  ],
] satisfies ToolPermissionRow[]
