import { spawnSync } from "node:child_process"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

const localEnvPath = path.join(process.cwd(), ".env.local")
const sharedEnvFilename = "milo.env.local"

const requiredLocalEnv = [
  "CONVEX_DEPLOYMENT",
  "VITE_CONVEX_URL",
  "VITE_CONVEX_SITE_URL",
  "VITE_CLERK_PUBLISHABLE_KEY",
  "CLERK_JWT_ISSUER_DOMAIN",
] as const

type Command = "check" | "run" | "setup"

const command = process.argv[2] as Command | undefined

if (command === "check") {
  checkEnv()
} else if (command === "setup") {
  setupSharedEnv()
} else if (command === "run") {
  runWithEnv(process.argv.slice(3))
} else {
  printUsageAndExit()
}

function checkEnv() {
  const resolved = resolveEnv()
  const missing = missingRequiredEnv(resolved.env)

  if (missing.length > 0) {
    printMissingEnv(missing, resolved.sources)
    process.exit(1)
  }

  process.stdout.write(
    [
      "Local environment is ready.",
      `Loaded: ${formatSources(resolved.sources)}`,
      "",
    ].join("\n")
  )
}

function setupSharedEnv() {
  const sharedEnvPath = getSharedEnvPath()

  if (sharedEnvPath === null) {
    throw new Error("Unable to find the git common directory.")
  }

  if (!existsSync(localEnvPath)) {
    throw new Error(
      "Missing .env.local. Copy .env.local.example to .env.local and fill it in first."
    )
  }

  const localEnv = readEnvFile(localEnvPath)
  const sharedEnv = { ...localEnv }

  for (const name of requiredLocalEnv) {
    const inheritedValue = process.env[name]

    if (
      isEmpty(sharedEnv[name]) &&
      inheritedValue !== undefined &&
      inheritedValue.trim() !== ""
    ) {
      sharedEnv[name] = inheritedValue
    }
  }

  const missing = missingRequiredEnv(sharedEnv)

  if (missing.length > 0) {
    printMissingEnv(missing, [localEnvPath])
    process.exit(1)
  }

  writeFileSync(sharedEnvPath, serializeEnv(sharedEnv), { mode: 0o600 })
  process.stdout.write(
    [
      `Wrote shared local environment to ${sharedEnvPath}.`,
      "All git worktrees for this repository can now use pnpm run deploy.",
      "",
    ].join("\n")
  )
}

function runWithEnv(args: string[]) {
  if (args.length === 0) {
    throw new Error("Missing command to run.")
  }

  const resolved = resolveEnv()
  const missing = missingRequiredEnv(resolved.env)

  if (missing.length > 0) {
    printMissingEnv(missing, resolved.sources)
    process.exit(1)
  }

  const result = spawnSync(args[0], args.slice(1), {
    env: resolved.env,
    stdio: "inherit",
  })

  process.exit(result.status ?? 1)
}

function resolveEnv() {
  const sharedEnvPath = getSharedEnvPath()
  const env = { ...process.env }
  const sources: string[] = []

  for (const source of [sharedEnvPath, localEnvPath]) {
    if (source === null || !existsSync(source)) {
      continue
    }

    Object.assign(env, readEnvFile(source))
    sources.push(source)
  }

  Object.assign(env, process.env)

  return { env, sources }
}

function getSharedEnvPath() {
  const result = spawnSync("git", ["rev-parse", "--git-common-dir"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  })

  if (result.status !== 0) {
    return null
  }

  return path.join(
    path.resolve(process.cwd(), result.stdout.trim()),
    sharedEnvFilename
  )
}

function readEnvFile(filePath: string) {
  const env: Record<string, string> = {}

  for (const line of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim()

    if (trimmed === "" || trimmed.startsWith("#")) {
      continue
    }

    const withoutExport = trimmed.startsWith("export ")
      ? trimmed.slice("export ".length).trim()
      : trimmed
    const separator = withoutExport.indexOf("=")

    if (separator === -1) {
      continue
    }

    const name = withoutExport.slice(0, separator).trim()
    const rawValue = withoutExport.slice(separator + 1).trim()

    if (!/^[A-Z_][A-Z0-9_]*$/.test(name)) {
      continue
    }

    env[name] = parseEnvValue(rawValue)
  }

  return env
}

function parseEnvValue(value: string) {
  if (value.length < 2) {
    return value
  }

  const quote = value[0]
  const last = value[value.length - 1]

  if ((quote === '"' || quote === "'") && last === quote) {
    return value.slice(1, -1)
  }

  return value
}

function serializeEnv(env: Record<string, string>) {
  return [
    "# Generated by `pnpm env:setup`.",
    "# Keep this file out of git; it is shared by local git worktrees.",
    "",
    ...Object.entries(env)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([name, value]) => `${name}=${formatEnvValue(value)}`),
    "",
  ].join("\n")
}

function formatEnvValue(value: string) {
  if (/^[^\s'"#]+$/.test(value)) {
    return value
  }

  return JSON.stringify(value)
}

function missingRequiredEnv(env: Record<string, string | undefined>) {
  return requiredLocalEnv.filter((name) => isEmpty(env[name]))
}

function isEmpty(value: string | undefined) {
  return value === undefined || value.trim() === ""
}

function printMissingEnv(
  missing: readonly string[],
  sources: readonly string[]
) {
  process.stderr.write(
    [
      `Missing required local environment: ${missing.join(", ")}`,
      `Loaded: ${formatSources(sources)}`,
      "Fix .env.local, then run `pnpm env:setup` once to share it with all local worktrees.",
      "",
    ].join("\n")
  )
}

function formatSources(sources: readonly string[]) {
  return sources.length === 0 ? "no env files" : sources.join(", ")
}

function printUsageAndExit(): never {
  process.stderr.write(
    [
      "Usage:",
      "  pnpm env:check",
      "  pnpm env:setup",
      "  pnpm env:run <command> [...args]",
      "",
    ].join("\n")
  )
  process.exit(1)
}
