import { spawnSync } from "node:child_process"
import { createHash } from "node:crypto"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { runtimeAssets } from "../runtime/artifacts/_generated/assets.ts"
import { root } from "./runtime/paths.ts"

const generatedPath = path.join(
  root,
  "convex/artifacts/templates/_generated/templates.ts"
)

export async function compileArtifactTemplates(checkMode: boolean) {
  const runtime = await fs.mkdtemp(path.join(os.tmpdir(), "milo-templates-"))

  try {
    const template = path.join(runtime, "template")
    await writeFiles(template, runtimeAssets.artifact.template)
    const configPath = path.join(runtime, "builder.json")
    await fs.writeFile(
      configPath,
      JSON.stringify({ artifactTemplatePath: template }),
      "utf8"
    )
    process.env.MILO_WORKSPACE = root
    process.env.MILO_ARTIFACT_BUILDER_CONFIG = configPath

    const { buildArtifact } = await import(
      "../runtime/artifacts/builder/index.ts"
    )
    const briefing = await buildArtifact([
      {
        path: "src/App.tsx",
        content: await readSource("briefing/app.txt"),
      },
      {
        path: "src/Briefing.tsx",
        content: await readSource("briefing/briefing.txt"),
      },
      {
        path: "src/contract.ts",
        content: await readSource("briefing/contract.txt"),
      },
      {
        path: "src/revision.ts",
        content: `export const artifactRuntimeRevision = "${runtimeRevision()}"\n`,
      },
    ])
    const content = formatGenerated(
      renderGenerated({ "meeting-briefing": briefing })
    )

    if (checkMode) {
      const existing = await fs.readFile(generatedPath, "utf8").catch(() => "")

      if (existing !== content) {
        throw new Error(
          "Artifact templates are stale. Run `pnpm templates:compile` and commit the result."
        )
      }

      return
    }

    await fs.mkdir(path.dirname(generatedPath), { recursive: true })
    await fs.writeFile(generatedPath, content, "utf8")
  } finally {
    await fs.rm(runtime, { force: true, recursive: true })
  }
}

function runtimeRevision() {
  return createHash("sha256")
    .update(JSON.stringify(runtimeAssets.artifact.template))
    .digest("hex")
}

async function readSource(relativePath: string) {
  return await fs.readFile(
    path.join(root, "playbooks/templates", relativePath),
    "utf8"
  )
}

async function writeFiles(directory: string, files: Record<string, string>) {
  for (const [relativePath, content] of Object.entries(files)) {
    const destination = path.join(directory, relativePath)
    await fs.mkdir(path.dirname(destination), { recursive: true })
    await fs.writeFile(destination, content, "utf8")
  }
}

function renderGenerated(value: unknown) {
  return [
    "/* biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated artifact source */\n",
    "// Generated by scripts/templates.ts. Do not edit by hand.\n",
    "export const playbookTemplates = ",
    JSON.stringify(value, null, 2),
    " as const\n",
  ].join("")
}

function formatGenerated(content: string) {
  const result = spawnSync(
    path.join(root, "node_modules/.bin/biome"),
    ["format", "--stdin-file-path", generatedPath],
    { encoding: "utf8", input: content }
  )

  if (result.status !== 0) {
    throw new Error(result.stderr || "Could not format artifact templates.")
  }

  return result.stdout
}

await compileArtifactTemplates(process.argv.includes("--check"))
