import { spawnSync } from "node:child_process"
import { createHash } from "node:crypto"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { runtimeAssets } from "../runtime/artifacts/_generated/assets.ts"
import { root } from "./runtime/paths.ts"

const generatedPath = path.join(
  root,
  "convex/artifacts/templates/_generated/templates.ts"
)
const summaryPath = path.join(root, "contracts/playbooks/generated.ts")

export async function compileArtifactTemplates(checkMode: boolean) {
  const runtime = await fs.mkdtemp(path.join(os.tmpdir(), "milo-templates-"))

  try {
    const template = path.join(runtime, "template")
    await writeFiles(template, runtimeAssets.artifact.template)
    const configPath = path.join(runtime, "builder.json")
    await fs.writeFile(
      configPath,
      JSON.stringify({ artifactTemplatePath: template }),
      "utf8"
    )
    process.env.MILO_WORKSPACE = root
    process.env.MILO_ARTIFACT_BUILDER_CONFIG = configPath

    const { buildArtifact } = await import(
      "../runtime/artifacts/builder/index.ts"
    )
    const briefing = await buildArtifact([
      {
        path: "src/App.tsx",
        content: await readSource("briefing/app.txt"),
      },
      {
        path: "src/Briefing.tsx",
        content: await readSource("briefing/briefing.txt"),
      },
      {
        path: "src/contract.ts",
        content: await readSource("briefing/contract.txt"),
      },
      {
        path: "src/revision.ts",
        content: `export const artifactRuntimeRevision = "${runtimeRevision()}"\n`,
      },
    ])
    const templates = { "meeting-briefing": briefing }
    const content = format(generatedPath, renderGenerated(templates))
    const summary = format(summaryPath, renderSummary(templates))

    if (checkMode) {
      await requireCurrent(generatedPath, content)
      await requireCurrent(summaryPath, summary)

      return
    }

    await fs.mkdir(path.dirname(generatedPath), { recursive: true })
    await fs.writeFile(generatedPath, content, "utf8")
    await fs.writeFile(summaryPath, summary, "utf8")
  } finally {
    await fs.rm(runtime, { force: true, recursive: true })
  }
}

async function requireCurrent(filePath: string, content: string) {
  const existing = await fs.readFile(filePath, "utf8").catch(() => "")

  if (existing !== content) {
    throw new Error(
      "Artifact templates are stale. Run `pnpm templates:compile` and commit the result."
    )
  }
}

function runtimeRevision() {
  return createHash("sha256")
    .update(JSON.stringify(runtimeAssets.artifact.template))
    .digest("hex")
}

async function readSource(relativePath: string) {
  return await fs.readFile(
    path.join(root, "playbooks/templates", relativePath),
    "utf8"
  )
}

async function writeFiles(directory: string, files: Record<string, string>) {
  for (const [relativePath, content] of Object.entries(files)) {
    const destination = path.join(directory, relativePath)
    await fs.mkdir(path.dirname(destination), { recursive: true })
    await fs.writeFile(destination, content, "utf8")
  }
}

function renderGenerated(value: unknown) {
  return [
    "/* biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated artifact source */\n",
    "// Generated by scripts/templates.ts. Do not edit by hand.\n",
    "export const playbookTemplates = ",
    JSON.stringify(value, null, 2),
    " as const\n",
  ].join("")
}

type CompiledTemplates = Record<
  string,
  { contract: { state: ContractStateEntry[] } }
>

type ContractStateEntry = {
  name: string
  scope: string
  description?: string
  schemaName: string
  schemaVersion: number
  schema: unknown
}

/** The client-side contract summary: what each template's state holds —
 *  including the enforced JSON Schema — so the console can describe a
 *  not-yet-provisioned artifact without the server-only template payload. */
function renderSummary(templates: CompiledTemplates) {
  const summaries = Object.fromEntries(
    Object.entries(templates).map(([key, template]) => [
      key,
      template.contract.state.map((entry) => ({
        name: entry.name,
        scope: entry.scope,
        description: entry.description,
        schemaName: entry.schemaName,
        schemaVersion: entry.schemaVersion,
        schema: entry.schema,
      })),
    ])
  )

  return [
    "/* biome-ignore-all lint/style/noExcessiveLinesPerFile: generated contract data */\n",
    "// Generated by scripts/templates.ts. Do not edit by hand.\n",
    "export const playbookTemplateContracts = ",
    JSON.stringify(summaries, null, 2),
    " as const\n",
  ].join("")
}

function format(filePath: string, content: string) {
  const result = spawnSync(
    path.join(root, "node_modules/.bin/biome"),
    ["format", "--stdin-file-path", filePath],
    { encoding: "utf8", input: content }
  )

  if (result.status !== 0) {
    throw new Error(result.stderr || "Could not format artifact templates.")
  }

  return result.stdout
}

await compileArtifactTemplates(process.argv.includes("--check"))
