import { githubToolPermissionRows } from "./github"
import { googleToolPermissionRows } from "./google"
import { type ToolPermissionRow } from "./index"
import { notionToolPermissionRows } from "./notion"

export const toolPermissionRows = [
  [
    "milo",
    "list_capabilities",
    "List capabilities",
    "List current run tools, connected integration capabilities, and integrations available to connect.",
    "read",
    "required",
  ],
  [
    "milo",
    "save_attachment",
    "Save attachment",
    "Persist a generated sandbox file as a run attachment for tools that send attachments.",
    "write",
    "required",
  ],
  [
    "milo",
    "search_attachments",
    "Search attachments",
    "Find saved run attachments that can be reused or sent.",
    "read",
  ],
  [
    "milo",
    "read_attachment",
    "Read attachment",
    "Inspect a saved run attachment by attachment ID.",
    "read",
  ],
  [
    "milo",
    "search_artifacts",
    "Search artifacts",
    "Find Milo artifacts.",
    "read",
  ],
  [
    "milo",
    "read_artifact",
    "Read artifact",
    "Inspect a Milo artifact source snapshot.",
    "read",
  ],
  [
    "milo",
    "read_artifact_state",
    "Read artifact state",
    "Read a scoped JSON state document for a Milo artifact.",
    "read",
  ],
  [
    "milo",
    "create_artifact",
    "Create artifact",
    "Validate, store, publish, and return the open path for a new Milo artifact.",
    "write",
  ],
  [
    "milo",
    "update_artifact",
    "Update artifact",
    "Validate, store, publish, and return the open path for a Milo artifact version.",
    "write",
  ],
  [
    "milo",
    "delete_artifact",
    "Delete artifact",
    "Archive an active artifact or permanently delete an archived artifact.",
    "write",
  ],
  [
    "milo",
    "update_artifact_state",
    "Update artifact state",
    "Replace or merge-patch a contract-bound state document for a Milo artifact.",
    "write",
  ],
  [
    "milo",
    "search_automations",
    "Search automations",
    "Find Milo automations.",
    "read",
  ],
  [
    "milo",
    "read_automation",
    "Read automation",
    "Inspect a Milo automation.",
    "read",
  ],
  [
    "milo",
    "add_automation",
    "Add automation",
    "Create a task that starts on a time or provider event trigger.",
    "write",
  ],
  [
    "milo",
    "update_automation",
    "Update automation",
    "Change a Milo automation.",
    "write",
  ],
  [
    "milo",
    "delete_automation",
    "Delete automation",
    "Delete a Milo automation.",
    "write",
  ],
  ["slack", "channels_list", "List channels", "List Slack channels.", "read"],
  [
    "slack",
    "conversations_history",
    "Read channel history",
    "Read Slack channel messages.",
    "read",
  ],
  [
    "slack",
    "conversations_replies",
    "Read thread replies",
    "Read Slack thread messages.",
    "read",
  ],
  [
    "slack",
    "conversations_search_messages",
    "Search messages",
    "Search Slack messages.",
    "read",
  ],
  ["slack", "users_search", "Search users", "Search Slack users.", "read"],
  [
    "slack",
    "conversations_add_message",
    "Send message",
    "Post a Slack message.",
    "write",
    "required",
  ],
  [
    "linear",
    "linear_search_issues",
    "Search issues",
    "Search Linear issues.",
    "read",
  ],
  ["linear", "linear_get_issue", "Read issue", "Read a Linear issue.", "read"],
  [
    "linear",
    "linear_list_comments",
    "Read comments",
    "Read Linear issue comments.",
    "read",
  ],
  [
    "linear",
    "linear_add_comment",
    "Add comment",
    "Add a Linear issue comment.",
    "write",
    "required",
  ],
  ...githubToolPermissionRows,
  ...googleToolPermissionRows,
  ...notionToolPermissionRows,
  [
    "microsoftEmail",
    "microsoft_email_search_messages",
    "Search messages",
    "Search Outlook messages.",
    "read",
  ],
  [
    "microsoftEmail",
    "microsoft_email_get_message",
    "Read message",
    "Read an Outlook message.",
    "read",
  ],
  [
    "microsoftEmail",
    "microsoft_email_send_message",
    "Send email",
    "Send an Outlook email.",
    "write",
  ],
  [
    "microsoftEmail",
    "microsoft_email_create_draft",
    "Create draft",
    "Create an Outlook draft.",
    "write",
  ],
  [
    "microsoftEmail",
    "microsoft_email_update_message",
    "Update message",
    "Update an Outlook message or draft.",
    "write",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_list_events",
    "List events",
    "List Microsoft Calendar events.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_get_event",
    "Read event",
    "Read a Microsoft Calendar event.",
    "read",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_create_event",
    "Create event",
    "Create a Microsoft Calendar event.",
    "write",
  ],
  [
    "microsoftCalendar",
    "microsoft_calendar_update_event",
    "Update event",
    "Update a Microsoft Calendar event.",
    "write",
  ],
] satisfies ToolPermissionRow[]
