import { type ToolPermissionRow } from "./index"

export const githubToolPermissionRows = [
  [
    "github",
    "github_list_repositories",
    "List repositories",
    "List the repositories Milo can access on GitHub.",
    "List repositories available to the GitHub installation. Use to discover repos before searching or reading one.",
    "read",
  ],
  [
    "github",
    "github_get_repository",
    "Read repository",
    "Read details about a GitHub repository.",
    "Read GitHub repository metadata such as default branch, visibility, and description. Use to confirm a repo before working in it.",
    "read",
  ],
  [
    "github",
    "github_search_issues",
    "Search issues and PRs",
    "Search issues and pull requests on GitHub.",
    "Search GitHub issues and pull requests by query. Use to find relevant items before reading them in full.",
    "read",
  ],
  [
    "github",
    "github_get_issue",
    "Read issue",
    "Read a GitHub issue or pull request discussion.",
    "Read a GitHub issue or pull request conversation. Use to get the full thread before replying or summarizing.",
    "read",
  ],
  [
    "github",
    "github_get_pull_request",
    "Read pull request",
    "Read details about a GitHub pull request.",
    "Read GitHub pull request metadata such as state, branches, and mergeability. Use alongside the conversation when acting on a PR.",
    "read",
  ],
  [
    "github",
    "github_get_file",
    "Read file",
    "Read a file or folder from a GitHub repository.",
    "Read a repository file or list a directory. Use to inspect code or docs without cloning the whole repo.",
    "read",
  ],
  [
    "github",
    "github_clone_repository",
    "Clone repository",
    "Clone a GitHub repository into Milo's workspace.",
    "Clone a repo into /home/user/workspace/<repo> as a real Git working copy. Use this instead of git clone in bash when you need the full tree or to run commands against it.",
    "read",
  ],
  [
    "github",
    "github_add_issue_comment",
    "Add issue comment",
    "Comment on a GitHub issue or pull request.",
    "Post a comment on a GitHub issue or pull request. Use to reply or post findings; confirm the target before sending.",
    "write",
    "required",
  ],
  [
    "github",
    "github_reply_to_pull_request_review_comment",
    "Reply to review comment",
    "Reply to an inline review comment on a GitHub pull request.",
    "Post a reply to a specific inline PR review comment. Use to respond in-thread rather than adding a top-level comment.",
    "write",
    "required",
  ],
] satisfies ToolPermissionRow[]
