import { type ToolPermissionRow } from "./index"

export const googleToolPermissionRows = [
  [
    "gmail",
    "google_gmail_search_threads",
    "Search threads",
    "Search your Gmail threads.",
    "Search Gmail threads by query. Use to narrow to relevant threads before reading; prefer the batch read for several hits.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_thread",
    "Read thread",
    "Read a Gmail thread.",
    "Read one Gmail thread in full. Use after search to get the messages before replying or summarizing.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_threads",
    "Read threads",
    "Read several Gmail threads at once.",
    "Read multiple Gmail threads in one call. Prefer this over repeated single-thread reads after a search.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_message",
    "Read message",
    "Read a single Gmail message.",
    "Read one Gmail message by id. Use when you need a specific message rather than the whole thread.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_messages",
    "Read messages",
    "Read several Gmail messages at once.",
    "Read multiple Gmail messages in one call. Prefer this over repeated single-message reads.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_reply_to_thread",
    "Reply to thread",
    "Reply to a Gmail thread.",
    "Reply to the latest message in a Gmail thread. Use to continue an existing conversation rather than starting a new one.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_send_message",
    "Send email",
    "Send a new email from your Gmail account.",
    "Send a new Gmail email. Use for a fresh message; reply to a thread instead when continuing a conversation.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_create_draft",
    "Create draft",
    "Save a Gmail draft without sending.",
    "Create a Gmail draft for the user to review and send. Prefer this over sending when the user should approve the email first.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_list_events",
    "List events",
    "List events on your Google Calendar.",
    "List Google Calendar events in a time range. Use to check availability or find an event before reading or changing it.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_get_event",
    "Read event",
    "Read a Google Calendar event.",
    "Read one Google Calendar event's details. Use to confirm specifics before updating or referencing it.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_create_event",
    "Create event",
    "Add an event to your Google Calendar.",
    "Create a Google Calendar event. Confirm time, attendees, and title before creating.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_update_event",
    "Update event",
    "Change an event on your Google Calendar.",
    "Update an existing Google Calendar event. Read it first to preserve fields you are not changing.",
    "write",
  ],
  [
    "googleDrive",
    "google_drive_search_files",
    "Search files",
    "Search files in your Google Drive.",
    "Search the connected Google Drive by name or content. Use to locate a file before reading it.",
    "read",
  ],
  [
    "googleDrive",
    "google_drive_get_file",
    "Read metadata",
    "Read details about a Google Drive file.",
    "Read Google Drive file metadata such as name, type, and owners. Use to confirm a file before reading its contents.",
    "read",
  ],
  [
    "googleDrive",
    "google_drive_read_file",
    "Read file content",
    "Read the contents of a Google Drive file.",
    "Download or export a Drive file's text content. Use to read a document's body, not just its metadata.",
    "read",
  ],
  [
    "googleDrive",
    "google_drive_create_file",
    "Create file",
    "Create a file in your Google Drive.",
    "Create a Google Drive file. Use to save new content the user wants stored in Drive.",
    "write",
  ],
  [
    "googleDrive",
    "google_drive_update_file",
    "Update file",
    "Update a Google Drive file.",
    "Update a Drive file's metadata or content. Read it first when changing content to avoid overwriting.",
    "write",
  ],
] satisfies ToolPermissionRow[]
