import { type ToolPermissionRow } from "./index"

export const googleToolPermissionRows = [
  [
    "gmail",
    "google_gmail_search_threads",
    "Search threads",
    "Search Gmail threads.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_thread",
    "Read thread",
    "Read a Gmail thread.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_threads",
    "Read threads",
    "Read multiple Gmail threads.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_message",
    "Read message",
    "Read a Gmail message.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_get_messages",
    "Read messages",
    "Read multiple Gmail messages.",
    "read",
  ],
  [
    "gmail",
    "google_gmail_reply_to_thread",
    "Reply to thread",
    "Reply to the latest message in a Gmail thread.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_send_message",
    "Send email",
    "Send a new Gmail email.",
    "write",
  ],
  [
    "gmail",
    "google_gmail_create_draft",
    "Create draft",
    "Create a Gmail draft.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_list_events",
    "List events",
    "List Google Calendar events.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_get_event",
    "Read event",
    "Read a Google Calendar event.",
    "read",
  ],
  [
    "googleCalendar",
    "google_calendar_create_event",
    "Create event",
    "Create a Google Calendar event.",
    "write",
  ],
  [
    "googleCalendar",
    "google_calendar_update_event",
    "Update event",
    "Update a Google Calendar event.",
    "write",
  ],
  [
    "googleDrive",
    "google_drive_search_files",
    "Search files",
    "Search files in the connected Google Drive.",
    "read",
  ],
  [
    "googleDrive",
    "google_drive_get_file",
    "Read metadata",
    "Read Google Drive file metadata.",
    "read",
  ],
  [
    "googleDrive",
    "google_drive_read_file",
    "Read file content",
    "Download or export Google Drive file text content.",
    "read",
  ],
  [
    "googleDrive",
    "google_drive_create_file",
    "Create file",
    "Create a Google Drive file.",
    "write",
  ],
  [
    "googleDrive",
    "google_drive_update_file",
    "Update file",
    "Update Google Drive file metadata or content.",
    "write",
  ],
] satisfies ToolPermissionRow[]
