import { type ToolPermissionRow } from "./index"

export const miloToolPermissionRows = [
  [
    "milo",
    "list_capabilities",
    "List capabilities",
    "List current run tools, connected integration capabilities, and integrations available to connect.",
    "read",
    "required",
  ],
  [
    "milo",
    "load_skill",
    "Load skill",
    "Load full instructions for an available Milo skill.",
    "read",
    "required",
  ],
  [
    "milo",
    "offer_integration",
    "Offer integration",
    "Create a Milo integration offer for an integration and offer it in the current interactive surface when possible. Include a concise summary for the integration offer card. Set wait to true to pause the run until the integration is connected when you need it to continue.",
    "write",
    "required",
  ],
  [
    "milo",
    "cancel_approval_request",
    "Cancel approval request",
    "Withdraw a pending approval request in this run. Requires a short reason and the Milo internal message id for the user message that requested cancellation.",
    "write",
    "required",
  ],
  [
    "milo",
    "cancel_integration_offer",
    "Cancel integration offer",
    "Withdraw a pending integration offer you previously made in this run. Requires a short reason.",
    "write",
    "required",
  ],
  [
    "milo",
    "save_asset",
    "Save asset",
    "Save a sandbox file as a run asset.",
    "write",
    "required",
  ],
  [
    "milo",
    "generate_image",
    "Generate image",
    "Generate image asset.",
    "write",
  ],
  [
    "milo",
    "search_assets",
    "Search assets",
    "Find saved run assets that can be reused or sent.",
    "read",
  ],
  [
    "milo",
    "read_asset",
    "Read asset",
    "Inspect a saved run asset by asset ID.",
    "read",
  ],
] satisfies ToolPermissionRow[]
