import { type ToolPermissionRow } from "./index"

export const miloToolPermissionRows = [
  [
    "milo",
    "list_capabilities",
    "List capabilities",
    "List current run tools, connected integration capabilities, and integrations available to connect.",
    "read",
    "required",
  ],
  [
    "milo",
    "load_skill",
    "Load skill",
    "Load full instructions for an available Milo skill.",
    "read",
    "required",
  ],
  [
    "milo",
    "offer_integration_setup",
    "Offer integration setup",
    "Create a Milo setup link for an integration and offer it in the current interactive surface when possible. Include a concise summary for the setup offer card. Set wait to true to pause the run until the integration is connected when you need it to continue.",
    "write",
    "required",
  ],
  [
    "milo",
    "cancel_approval_request",
    "Cancel approval request",
    "Withdraw a pending approval request you previously made in this run. Requires a short reason.",
    "write",
    "required",
  ],
  [
    "milo",
    "cancel_connection_offer",
    "Cancel connection offer",
    "Withdraw a pending integration setup offer you previously made in this run. Requires a short reason.",
    "write",
    "required",
  ],
  [
    "milo",
    "save_attachment",
    "Save attachment",
    "Save a sandbox file as a run attachment.",
    "write",
    "required",
  ],
  [
    "milo",
    "generate_image",
    "Generate image",
    "Generate image attachment.",
    "write",
  ],
  [
    "milo",
    "search_attachments",
    "Search attachments",
    "Find saved run attachments that can be reused or sent.",
    "read",
  ],
  [
    "milo",
    "read_attachment",
    "Read attachment",
    "Inspect a saved run attachment by attachment ID.",
    "read",
  ],
] satisfies ToolPermissionRow[]
