import { type ToolPermissionRow } from "./index"

export const notionToolPermissionRows = [
  [
    "notion",
    "notion_search",
    "Search Notion",
    "Search the Notion pages and databases shared with Milo.",
    "Search shared Notion pages and databases by query. Use to locate a page or database before reading it.",
    "read",
  ],
  [
    "notion",
    "notion_get_page",
    "Read page",
    "Read a Notion page's properties.",
    "Read a Notion page's properties. Use to inspect its fields; read block children for the page body.",
    "read",
  ],
  [
    "notion",
    "notion_get_block_children",
    "Read page content",
    "Read the contents of a Notion page.",
    "Read a Notion block's children to get page body content. Use after finding a page to read what is on it.",
    "read",
  ],
  [
    "notion",
    "notion_query_data_source",
    "Query data source",
    "Query a Notion database.",
    "Query a Notion data source or database with filters and sorts. Use to pull records rather than free-text searching.",
    "read",
  ],
  [
    "notion",
    "notion_list_comments",
    "Read comments",
    "Read comments on a Notion page.",
    "Read comments on a Notion page or block. Use to see discussion before replying.",
    "read",
  ],
  [
    "notion",
    "notion_create_page",
    "Create page",
    "Create a Notion page or database record.",
    "Create a Notion page or database record. Confirm the parent and properties before creating.",
    "write",
  ],
  [
    "notion",
    "notion_update_page",
    "Update page",
    "Update a Notion page or its archive state.",
    "Update a Notion page's properties or archive it. Read it first to preserve fields you are not changing.",
    "write",
  ],
  [
    "notion",
    "notion_upload_file",
    "Upload file",
    "Upload a saved file to Notion.",
    "Upload a saved run asset to Notion for a page icon, cover, or file property. Save the asset first, then reference it here.",
    "write",
  ],
  [
    "notion",
    "notion_append_block_children",
    "Append blocks",
    "Add content to a Notion page.",
    "Append blocks to a Notion page or block. Use to add body content after creating or finding a page.",
    "write",
  ],
  [
    "notion",
    "notion_create_comment",
    "Add comment",
    "Comment on a Notion page.",
    "Add a comment or discussion reply on a Notion page. Use to respond in-thread.",
    "write",
  ],
] satisfies ToolPermissionRow[]
