/** Capabilities relevant to prompt injection, reviewed per tool. An empty
 * list means none of these capabilities, not that a tool is risk-free.
 * Content reads include text other people can supply. Web queries, URLs,
 * and networked commands can carry data out even without a send tool. */
export type ToolRisk = "private" | "untrusted" | "outbound"

export const toolRisks: Readonly<Record<string, readonly ToolRisk[]>> = {
  search_tables: ["private"],
  read_table: ["private"],
  list_table_rows: ["private", "untrusted"],
  create_table: [],
  insert_table_row: [],
  update_table_row: [],
  delete_table_row: [],
  share_table: ["outbound"],
  search_stores: ["private"],
  read_store: ["private", "untrusted"],
  create_store: [],
  write_store: [],
  share_store: ["outbound"],
  share_file: ["outbound"],
  list_capabilities: [],
  load_skill: [],
  search_runs: ["private", "untrusted"],
  search_run_activity: ["private", "untrusted"],
  offer_integration: [],
  cancel_approval_request: [],
  cancel_integration_offer: [],
  save_file: [],
  generate_image: [],
  search_files: ["private"],
  read_file: ["private", "untrusted"],
  search_jobs: ["private"],
  read_job: ["private", "untrusted"],
  add_job: [],
  update_job: [],
  delete_job: [],
  web_search: ["untrusted", "outbound"],
  web_fetch: ["untrusted", "outbound"],
  finish_run: [],
  send_reply: ["outbound"],
  add_reaction: [],
  read: ["private", "untrusted"],
  grep: ["private", "untrusted"],
  glob: ["private"],
  git: ["private", "untrusted"],
  apply_patch: [],
  bash: ["untrusted", "outbound"],
  start_agent: [],
  wait_for_agents: [],
  stop_agent: [],
  channels_list: ["private"],
  conversations_history: ["private", "untrusted"],
  conversations_replies: ["private", "untrusted"],
  conversations_search_messages: ["private", "untrusted"],
  users_search: ["private"],
  conversations_add_message: ["outbound"],
  slack_add_reaction: [],
  linear_search_issues: ["private", "untrusted"],
  linear_get_issue: ["private", "untrusted"],
  linear_list_comments: ["private", "untrusted"],
  linear_add_comment: ["outbound"],
  linear_add_reaction: [],
  github_list_repositories: ["private"],
  github_get_repository: ["private"],
  github_search_issues: ["private", "untrusted"],
  github_get_issue: ["private", "untrusted"],
  github_get_pull_request: ["private", "untrusted"],
  github_get_file: ["private", "untrusted"],
  github_clone_repository: ["private", "untrusted"],
  github_add_issue_comment: ["outbound"],
  github_reply_to_pull_request_review_comment: ["outbound"],
  github_list_pull_request_files: ["private", "untrusted"],
  github_list_pull_request_review_comments: ["private", "untrusted"],
  github_commit_to_pull_request: ["outbound"],
  github_create_pull_request: ["outbound"],
  github_add_comment_reaction: [],
  github_update_pull_request: ["outbound"],
  google_gmail_search_threads: ["private", "untrusted"],
  google_gmail_get_thread: ["private", "untrusted"],
  google_gmail_get_threads: ["private", "untrusted"],
  google_gmail_get_message: ["private", "untrusted"],
  google_gmail_get_messages: ["private", "untrusted"],
  google_gmail_reply_to_thread: ["outbound"],
  google_gmail_send_message: ["outbound"],
  google_gmail_create_draft: [],
  google_calendar_list_calendars: ["private"],
  google_calendar_list_events: ["private", "untrusted"],
  google_calendar_get_event: ["private", "untrusted"],
  google_calendar_create_event: ["outbound"],
  google_calendar_update_event: ["outbound"],
  notion_search: ["private", "untrusted"],
  notion_get_page: ["private", "untrusted"],
  notion_get_block_children: ["private", "untrusted"],
  notion_query_data_source: ["private", "untrusted"],
  notion_list_comments: ["private", "untrusted"],
  notion_create_page: ["outbound"],
  notion_update_page: ["outbound"],
  notion_upload_file: ["outbound"],
  notion_append_block_children: ["outbound"],
  notion_create_comment: ["outbound"],
  microsoft_email_search_messages: ["private", "untrusted"],
  microsoft_email_get_message: ["private", "untrusted"],
  microsoft_email_send_message: ["outbound"],
  microsoft_email_create_draft: [],
  microsoft_email_update_message: [],
  microsoft_calendar_list_calendars: ["private"],
  microsoft_calendar_list_events: ["private", "untrusted"],
  microsoft_calendar_get_event: ["private", "untrusted"],
  microsoft_calendar_create_event: ["outbound"],
  microsoft_calendar_update_event: ["outbound"],
}

/** Assess the selected grants only. This is advice, never a save gate or a
 * claim that a job without the combination is safe. */
export function assessToolRisk(tools: readonly string[]) {
  const groups: Record<ToolRisk, string[]> = {
    private: [],
    untrusted: [],
    outbound: [],
  }
  for (const tool of new Set(tools)) {
    for (const risk of toolRisks[tool] ?? []) {
      groups[risk].push(tool)
    }
  }
  return {
    groups,
    warning: Object.values(groups).every((group) => group.length > 0),
  }
}
