/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ContextRouteImport } from './routes/context'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts/index'
import { Route as ContextIndexRouteImport } from './routes/context/index'
import { Route as ContextPlacesRouteImport } from './routes/context/places'
import { Route as ContextWorkstreamsRouteImport } from './routes/context/workstreams'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ArtifactsArtifactIdIndexRouteImport } from './routes/artifacts/$artifactId/index'
import { Route as IntegrationsOffersTokenRouteImport } from './routes/integrations/offers/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ContextIndexRoute = ContextIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContextRoute,
} as any)
const ContextPlacesRoute = ContextPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => ContextRoute,
} as any)
const ContextWorkstreamsRoute = ContextWorkstreamsRouteImport.update({
  id: '/workstreams',
  path: '/workstreams',
  getParentRoute: () => ContextRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsArtifactIdIndexRoute =
  ArtifactsArtifactIdIndexRouteImport.update({
    id: '/$artifactId/',
    path: '/$artifactId/',
    getParentRoute: () => ArtifactsRoute,
  } as any)
const IntegrationsOffersTokenRoute = IntegrationsOffersTokenRouteImport.update({
  id: '/offers/$token',
  path: '/offers/$token',
  getParentRoute: () => IntegrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/console': typeof ConsoleRoute
  '/context': typeof ContextRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/runs': typeof RunsRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/skills': typeof SkillsRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/context/places': typeof ContextPlacesRoute
  '/context/workstreams': typeof ContextWorkstreamsRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/context/': typeof ContextIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations/offers/$token': typeof IntegrationsOffersTokenRoute
  '/artifacts/$artifactId/': typeof ArtifactsArtifactIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/console': typeof ConsoleRoute
  '/playbooks': typeof PlaybooksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/runs': typeof RunsRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/skills': typeof SkillsRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/context/places': typeof ContextPlacesRoute
  '/context/workstreams': typeof ContextWorkstreamsRoute
  '/artifacts': typeof ArtifactsIndexRoute
  '/context': typeof ContextIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations/offers/$token': typeof IntegrationsOffersTokenRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/console': typeof ConsoleRoute
  '/context': typeof ContextRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/runs': typeof RunsRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/skills': typeof SkillsRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/context/places': typeof ContextPlacesRoute
  '/context/workstreams': typeof ContextWorkstreamsRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/context/': typeof ContextIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations/offers/$token': typeof IntegrationsOffersTokenRoute
  '/artifacts/$artifactId/': typeof ArtifactsArtifactIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/automations'
    | '/console'
    | '/context'
    | '/integrations'
    | '/playbooks'
    | '/pricing'
    | '/privacy'
    | '/runs'
    | '/sign-in'
    | '/sign-out'
    | '/skills'
    | '/terms'
    | '/trust'
    | '/context/places'
    | '/context/workstreams'
    | '/artifacts/'
    | '/context/'
    | '/integrations/'
    | '/api/auth/$'
    | '/integrations/offers/$token'
    | '/artifacts/$artifactId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/console'
    | '/playbooks'
    | '/pricing'
    | '/privacy'
    | '/runs'
    | '/sign-in'
    | '/sign-out'
    | '/skills'
    | '/terms'
    | '/trust'
    | '/context/places'
    | '/context/workstreams'
    | '/artifacts'
    | '/context'
    | '/integrations'
    | '/api/auth/$'
    | '/integrations/offers/$token'
    | '/artifacts/$artifactId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/automations'
    | '/console'
    | '/context'
    | '/integrations'
    | '/playbooks'
    | '/pricing'
    | '/privacy'
    | '/runs'
    | '/sign-in'
    | '/sign-out'
    | '/skills'
    | '/terms'
    | '/trust'
    | '/context/places'
    | '/context/workstreams'
    | '/artifacts/'
    | '/context/'
    | '/integrations/'
    | '/api/auth/$'
    | '/integrations/offers/$token'
    | '/artifacts/$artifactId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  AutomationsRoute: typeof AutomationsRoute
  ConsoleRoute: typeof ConsoleRoute
  ContextRoute: typeof ContextRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  PlaybooksRoute: typeof PlaybooksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RunsRoute: typeof RunsRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  SkillsRoute: typeof SkillsRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/context/': {
      id: '/context/'
      path: '/'
      fullPath: '/context/'
      preLoaderRoute: typeof ContextIndexRouteImport
      parentRoute: typeof ContextRoute
    }
    '/context/places': {
      id: '/context/places'
      path: '/places'
      fullPath: '/context/places'
      preLoaderRoute: typeof ContextPlacesRouteImport
      parentRoute: typeof ContextRoute
    }
    '/context/workstreams': {
      id: '/context/workstreams'
      path: '/workstreams'
      fullPath: '/context/workstreams'
      preLoaderRoute: typeof ContextWorkstreamsRouteImport
      parentRoute: typeof ContextRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$artifactId/': {
      id: '/artifacts/$artifactId/'
      path: '/$artifactId'
      fullPath: '/artifacts/$artifactId/'
      preLoaderRoute: typeof ArtifactsArtifactIdIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/integrations/offers/$token': {
      id: '/integrations/offers/$token'
      path: '/offers/$token'
      fullPath: '/integrations/offers/$token'
      preLoaderRoute: typeof IntegrationsOffersTokenRouteImport
      parentRoute: typeof IntegrationsRoute
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
  ArtifactsArtifactIdIndexRoute: typeof ArtifactsArtifactIdIndexRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsIndexRoute: ArtifactsIndexRoute,
  ArtifactsArtifactIdIndexRoute: ArtifactsArtifactIdIndexRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface ContextRouteChildren {
  ContextPlacesRoute: typeof ContextPlacesRoute
  ContextWorkstreamsRoute: typeof ContextWorkstreamsRoute
  ContextIndexRoute: typeof ContextIndexRoute
}

const ContextRouteChildren: ContextRouteChildren = {
  ContextPlacesRoute: ContextPlacesRoute,
  ContextWorkstreamsRoute: ContextWorkstreamsRoute,
  ContextIndexRoute: ContextIndexRoute,
}

const ContextRouteWithChildren =
  ContextRoute._addFileChildren(ContextRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  IntegrationsOffersTokenRoute: typeof IntegrationsOffersTokenRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  IntegrationsOffersTokenRoute: IntegrationsOffersTokenRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  AutomationsRoute: AutomationsRoute,
  ConsoleRoute: ConsoleRoute,
  ContextRoute: ContextRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  PlaybooksRoute: PlaybooksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RunsRoute: RunsRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  SkillsRoute: SkillsRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
