/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts/index'
import { Route as ArtifactsArtifactIdIndexRouteImport } from './routes/artifacts/$artifactId/index'
import { Route as IntegrationsSetupTokenRouteImport } from './routes/integrations/setup/$token'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ArtifactsArtifactIdIndexRoute =
  ArtifactsArtifactIdIndexRouteImport.update({
    id: '/$artifactId/',
    path: '/$artifactId/',
    getParentRoute: () => ArtifactsRoute,
  } as any)
const IntegrationsSetupTokenRoute = IntegrationsSetupTokenRouteImport.update({
  id: '/setup/$token',
  path: '/setup/$token',
  getParentRoute: () => IntegrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/console': typeof ConsoleRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/integrations/setup/$token': typeof IntegrationsSetupTokenRoute
  '/artifacts/$artifactId/': typeof ArtifactsArtifactIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/console': typeof ConsoleRoute
  '/playbooks': typeof PlaybooksRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/artifacts': typeof ArtifactsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/integrations/setup/$token': typeof IntegrationsSetupTokenRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/console': typeof ConsoleRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/integrations/setup/$token': typeof IntegrationsSetupTokenRoute
  '/artifacts/$artifactId/': typeof ArtifactsArtifactIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/automations'
    | '/console'
    | '/integrations'
    | '/playbooks'
    | '/runs'
    | '/skills'
    | '/artifacts/'
    | '/integrations/'
    | '/integrations/setup/$token'
    | '/artifacts/$artifactId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/console'
    | '/playbooks'
    | '/runs'
    | '/skills'
    | '/artifacts'
    | '/integrations'
    | '/integrations/setup/$token'
    | '/artifacts/$artifactId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/automations'
    | '/console'
    | '/integrations'
    | '/playbooks'
    | '/runs'
    | '/skills'
    | '/artifacts/'
    | '/integrations/'
    | '/integrations/setup/$token'
    | '/artifacts/$artifactId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  AutomationsRoute: typeof AutomationsRoute
  ConsoleRoute: typeof ConsoleRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  PlaybooksRoute: typeof PlaybooksRoute
  RunsRoute: typeof RunsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/artifacts/$artifactId/': {
      id: '/artifacts/$artifactId/'
      path: '/$artifactId'
      fullPath: '/artifacts/$artifactId/'
      preLoaderRoute: typeof ArtifactsArtifactIdIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/integrations/setup/$token': {
      id: '/integrations/setup/$token'
      path: '/setup/$token'
      fullPath: '/integrations/setup/$token'
      preLoaderRoute: typeof IntegrationsSetupTokenRouteImport
      parentRoute: typeof IntegrationsRoute
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
  ArtifactsArtifactIdIndexRoute: typeof ArtifactsArtifactIdIndexRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsIndexRoute: ArtifactsIndexRoute,
  ArtifactsArtifactIdIndexRoute: ArtifactsArtifactIdIndexRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  IntegrationsSetupTokenRoute: typeof IntegrationsSetupTokenRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  IntegrationsSetupTokenRoute: IntegrationsSetupTokenRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  AutomationsRoute: AutomationsRoute,
  ConsoleRoute: ConsoleRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  PlaybooksRoute: PlaybooksRoute,
  RunsRoute: RunsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
