import { humanizeToolName } from "./names"

export function getToolLabel(tool: string) {
  return toolLabels[tool] ?? humanizeToolName(tool)
}

const toolLabels: Record<string, string> = {
  add_automation: "Add automation",
  slack_add_reaction: "Add Slack reaction",
  channels_list: "List Slack channels",
  conversations_add_message: "Send Slack message",
  conversations_history: "Read Slack channel history",
  conversations_replies: "Read Slack thread replies",
  conversations_search_messages: "Search Slack messages",
  create_store: "Create store",
  create_table: "Create table",
  delete_automation: "Delete automation",
  delete_table_row: "Delete table row",
  generate_image: "Generate image",
  insert_table_row: "Insert table row",
  list_table_rows: "List table rows",
  google_calendar_create_event: "Create Google Calendar event",
  google_calendar_get_event: "Read Google Calendar event",
  google_calendar_list_calendars: "List Google calendars",
  google_calendar_list_events: "List Google Calendar events",
  google_calendar_update_event: "Update Google Calendar event",
  google_gmail_create_draft: "Create Gmail draft",
  google_gmail_get_message: "Read Gmail message",
  google_gmail_get_thread: "Read Gmail thread",
  google_gmail_reply_to_thread: "Reply to Gmail thread",
  google_gmail_search_threads: "Search Gmail threads",
  google_gmail_send_message: "Send Gmail email",
  github_add_comment_reaction: "Add GitHub comment reaction",
  github_add_issue_comment: "Add GitHub issue comment",
  github_clone_repository: "Clone GitHub repository",
  github_commit_to_pull_request: "Commit to GitHub pull request",
  github_create_pull_request: "Create GitHub pull request",
  github_get_file: "Read GitHub file",
  github_get_issue: "Read GitHub issue",
  github_get_pull_request: "Read GitHub pull request",
  github_get_repository: "Read GitHub repository",
  github_list_pull_request_files: "List GitHub pull request files",
  github_list_pull_request_review_comments:
    "List GitHub pull request review comments",
  github_list_repositories: "List GitHub repositories",
  github_search_issues: "Search GitHub issues and pull requests",
  github_update_pull_request: "Update GitHub pull request",
  linear_add_comment: "Add Linear comment",
  linear_add_reaction: "Add Linear reaction",
  linear_get_issue: "Read Linear issue",
  linear_list_comments: "Read Linear comments",
  linear_search_issues: "Search Linear issues",
  microsoft_calendar_create_event: "Create Microsoft Calendar event",
  microsoft_calendar_get_event: "Read Microsoft Calendar event",
  microsoft_calendar_list_calendars: "List Microsoft calendars",
  microsoft_calendar_list_events: "List Microsoft Calendar events",
  microsoft_calendar_update_event: "Update Microsoft Calendar event",
  microsoft_email_create_draft: "Create Outlook draft",
  microsoft_email_get_message: "Read Outlook message",
  microsoft_email_search_messages: "Search Outlook messages",
  microsoft_email_send_message: "Send Outlook email",
  microsoft_email_update_message: "Update Outlook message",
  notion_append_block_children: "Append Notion blocks",
  notion_create_comment: "Add Notion comment",
  notion_create_page: "Create Notion page",
  notion_get_block_children: "Read Notion page content",
  notion_get_page: "Read Notion page",
  notion_list_comments: "Read Notion comments",
  notion_query_data_source: "Query Notion data source",
  notion_search: "Search Notion",
  notion_update_page: "Update Notion page",
  notion_upload_file: "Upload Notion file",
  read_asset: "Read asset",
  read_automation: "Read automation",
  read_store: "Read store",
  read_table: "Read table",
  save_asset: "Save asset",
  search_assets: "Search assets",
  search_automations: "Search automations",
  search_stores: "Search stores",
  search_tables: "Search tables",
  update_automation: "Update automation",
  update_table_row: "Update table row",
  users_search: "Search Slack users",
  write_store: "Write store",
}
