import { type TableNames } from "../../_generated/dataModel"

// Children precede parents so ownership stays provable during every batch.
export const contentTables = [
  "emailSubmissions",
  "documents",
  "sessions",
  "drafts",
  "shares",
  "webhookDeliveries",
  "integrationInstalls",
  "integrationOffers",
  "transitions",
  "approvals",
  "waiters",
  "traces",
  "transcript",
  "usageReceipts",
  "usage",
  "messages",
  "events",
  "backfills",
  "subscriptions",
  "organizationSources",
  "organizationDiscovery",
  "organizationProfile",
  "evidence",
  "journal",
  "beliefs",
  "efforts",
  "passes",
  "reactions",
  "identities",
  "permissions",
  "skills",
  "files",
  "collections",
  "folders",
  "persons",
  "places",
  "jobs",
  "integrations",
  "runs",
  "conversations",
] as const satisfies readonly TableNames[]
